let COSAS = [
    "Vejiga de aire",
    "Petr&oacute;leo",
    "Esposas",
    "Cuerda corta",
    "Cuerda larga",
    "Antitoxina",
    "Gancho de agarre",
    "Pico",
    "Protecci&oacute;n espiritual",
    "Carro",
    "Saco grande",
    "Poste",
    "Catalejo",
    "Cadena",
    "Trampa grande",
    "Polea",
    "Yesquero",
    "Varilla de radiestesia",
    "Ganz&uacute;as",
    "Repelente",
    "Wolfsbane Tools",
    "Fuelle",
    "Ollas",
    "Grasa",
    "Red",
    "Cubo",
    "Palanca",
    "Martillo",
    "Sierra",
    "Abrojos",
    "Taladro",
    "Reloj de arena",
    "Sellador",
    "Tiza",
    "Ca&ntilde;a de pescar",
    "Lima de metal",
    "Pala",
    "Cincel",
    "Pegamento",
    "Clavos",
    "Pinzas",
    "Botella",
    "Cuerno",
    "Espejo",
    "Jab&oacute;n",
    "Baraja de cartas",
    "Incienso",
    "Perfume",
    "Esponja",
    "Juego de dados",
    "Instrumento",
    "Pluma y tinta",
    "Tarro",
    "Pintura facial",
    "Lentes",
    "Paquete de sal",
    "Hilo",
    "Joyas falsas",
    "Canicas",
    "Campana peque&ntilde;a",
    "Silbato",
    "Martillo de guerra",
    "Cetro",
    "Cota de malla",
    "T&uacute;nicas enga&ntilde;osas",
    "Guanteletes",
    "Incensario y hoja purificadora de agua bendita",
    "Jarra de vino de miel",
    "S&iacute;mbolo sagrado",
    "Cancionero popular",
    "Capa del carro de la orden",
    "Hoz de caballero zahor&iacute;",
    "Espada larga",
    "Jub&oacute;n de retazos",
    "Cota de malla",
    "Casco de varilla de radiestesia",
    "Piedra ocular",
    "Capa her&aacute;ldica",
    "Esposas de mapa gastadas",
    "Catalejo",
    "Cuerda fina",
    "Enano",
    "Usuario de magia",
    "Ra&iacute;z espinosa",
    "Bast&oacute;n efervescente",
    "Celos&iacute;a de pi&ntilde;a",
    "Daga",
    "Paleta Libro de hechizos",
    "Frasco de hormigas del bosque",
    "Hongo venenoso",
    "Ropa irregular",
    "Taladro de mano",
    "Espada elegante",
    "Arco largo",
    "Arco recurvo",
    "Arco largo plegable",
    "Hacha",
    "Ropa Dorada",
    "Cueros Acolchados",
    "Libro de Hechizos",
    "Trampa Grande",
    "Flauta Dorada",
    "Sabueso",
    "Cuerno de guerrero",
    "Dos Dagas",
    "Cimitarra",
    "Jub&oacute;n con capucha",
    "Espada corta",
    "Espada corta",
    "Ganz&uacute;as",
    "Abrojos",
    "Tabaco",
    "Juego de dados",
    "Gancho de agarre para bolsa",
    "Tuber&iacute;a",
    "Lima de metal",
    "Armadura",
    "Escudo",
    "Casco",
    "Gambeson (abrigo acolchado)",
    "Brigandina",
    "Cota de malla",
    "Placa",
    "Daga",
    "Cachiporra",
    "Hoz",
    "Bast&oacute;n",
    "Lanza",
    "Espada",
    "Maza",
    "Hacha",
    "Mayal",
    "Alabarda",
    "Martillo de guerra",
    "Espada larga",
    "Honda",
    "Arco",
    "Ballesta",
    "Equipo y herramientas",
    "C&aacute;mara de aire",
    "Trampa grande",
    "Fuelle",
    "Esponja grande",
    "Saco de dormir",
    "Lente",
    "Libro",
    "Ganz&uacute;as",
    "Cubo",
    "Esposas",
    "Abrojos",
    "Lima de metal",
    "Manzana",
    "Pera",
    "Tomate",
    "Naranja",
    "Lim&oacute;n",
    "Carro",
    "Espejo",
    "Cadena",
    "Mula",
    "Tiza",
    "Red de pesca",
    "Red de caza",
    "Cincel",
    "Bolsa de hule",
    "Ollas",
    "Pico",
    "Palanca",
    "Polea",
    "Taladro manual",
    "Poste",
    "Pintura facial",
    "Pluma y tinta",
    "Petr&oacute;leo",
    "Raciones para tres d&iacute;as",
    "Ca&ntilde;a de pescar",
    "Cuerda",
    "Canicas de vidrio",
    "Sierra",
    "Pegamento",
    "Saco",
    "Grasa",
    "Pala",
    "Gancho",
    "Jab&oacute;n",
    "Martillo",
    "P&uacute;a",
    "Agua bendita",
    "Botas con pinchos",
    "Cuerno",
    "Catalejo",
    "Caballo",
    "Brea",
    "Reloj de arena",
    "Tienda para 2 personas",
    "Incienso",
    "Antorcha",
    "Escalera de cuerda",
    "Vag&oacute;n",
    "Linterna y aceite",
    "Abaco",
    "Abrojos",
    "Aceite frasco",
    "Acido vial",
    "Agua bendita",
    "Alm&aacute;dena",
    "Ant&iacute;doto vial",
    "Antorcha",
    "Aparejos de pesca",
    "Aparejo de poleas",
    "Ariete port&aacute;til",
    "Balanza de mercader",
    "Barril",
    "Bolas de rodamientos",
    "Bolsa",
    "zurr&oacute;n",
    "Bolsa",
    "Botella de cristal",
    "Cadena",
    "C&aacute;lamo",
    "Campanilla",
    "Carcaj",
    "Catalejo",
    "Cerradura",
    "Cesta",
    "Cofre",
    "Cubo",
    "Cuerda de c&aacute;&ntilde;amo",
    "Cuerda de seda",
    "Equipo de cocina",
    "Equipo de curandero",
    "Equipo de escalada",
    "Escalera de mano",
    "Espejo de acero",
    "Estuche de virotes de ballesta",
    "Estuche de mapas o pergaminos",
    "Foco arcano",
    "Cetro Cristal",
    "Orbe",
    "Vara",
    "Varita",
    "Foco dru&iacute;dico",
    "Ramita de mu&eacute;rdago",
    "T&oacute;tem",
    "Vara de madera",
    "Varita de tejo",
    "Frasco o taza",
    "Fuego de alquimista",
    "Garfio",
    "Gancho",
    "Grilletes",
    "Candado",
    "Jab&oacute;n",
    "Jarro",
    "Jarra",
    "Lacre",
    "L&aacute;mpara",
    "Libro",
    "Linterna,",
    "Ojo de buey",
    "Linterna sorda o encapuchada",
    "Lupa",
    "Manta",
    "Martillo",
    "Mochila",
    "Munici&oacute;n",
    "Agujas de cerbatana",
    "Cerbatana",
    "Balas de honda",
    "Flechas",
    "Virotes de ballesta",
    "Odre",
    "Olla de hierro",
    "Pala",
    "Palanca",
    "Papel",
    "Perfume vial",
    "Pergamino una hoja",
    "P&eacute;rtiga",
    "Pico de minero",
    "Piedra de afilar",
    "Piquetas de hierro",
    "Pit&oacute;n",
    "Poci&oacute;n de curaci&oacute;n",
    "Raciones 1 d&iacute;a",
    "Reloj de arena",
    "Ropa Com&uacute;n",
    "Ropa Fina",
    "Ropa Elegante",
    "Ropa de Viajero",
    "T&uacute;nica",
    "Saco",
    "Saco de dormir",
    "Sello (anillo)",
    "Silbato de se&ntilde;ales",
    "S&iacute;mbolo sagrado",
    "Amuleto",
    "Emblema",
    "Relicario",
    "Tienda para dos personas",
    "Tinta (botellita)",
    "Tiza (trozo)",
    "Trampa de caza",
    "Vela",
    "Veneno b&aacute;sico (vial)",
    "Vial",
    "Yesquero",
    "Herramientas de artesano",
    "Materiales alqu&iacute;micos",
    "Materiales de cervecer&iacute;a",
    "Materiales de caligraf&iacute;a",
    "Herramientas de carpintero",
    "Herramientas de cart&oacute;grafo",
    "Herramientas de zapatero",
    "Utensilios de cocina",
    "Herramientas de soplador de vidrio",
    "Herramientas de joyero",
    "Herramientas de peletero",
    "Herramientas de alba&ntilde;il",
    "Materiales de pintor",
    "Herramientas de alfarero",
    "Herramientas de herrero",
    "Herramientas de calderero",
    "Herramientas de tejedor",
    "Herramientas de evanista",
    "Equipo de disfraz",
    "Equipo de falsificaci&oacute;n",
    "Set de juego",
    "Set de dados",
    "Set de ajedrez de drag&oacute;n",
    "Set de baraja de cartas",
    "Set de tres dragones de piedra",
    "Equipo de herbalismo",
    "Instrumentos musicales",
    "Gaita",
    "Tambor",
    "Dulcimer",
    "Flauta",
    "La&uacute;d",
    "Lira",
    "Cuerno",
    "Flauta de pan",
    "Caramillo",
    "Viola",
    "Herramientas de navegaci&oacute;n",
    "Equipo de veneno",
    "Herramientas de ladr&oacute;n",
    "Veh&iacute;culos terrestres",
    "Veh&iacute;culos acu&aacute;ticos",
    "Mochila",
    "Barril",
    "Cesta",
    "Botella",
    "Cubo",
    "Cofre",
    "Frasco",
    "Taza",
    "Jarro",
    "Jarra",
    "Olla de hierro",
    "Bolsa",
    "Saco",
    "Vial",
    "Odre",
    "Camello",
    "Burro",
    "Mula",
    "Elefante",
    "Caballo de tiro",
    "Caballo de monta",
    "Caballo de guerra",
    "Mast&iacute;n",
    "Pony",
    "Bardas",
    "Bocado y bridas",
    "Carreta",
    "Carro",
    "Carruaje",
    "Comida",
    "Sillas de montar",
    "Alforjas",
    "Establos",
    "Vag&oacute;n",
    "Galera",
    "Barcaza",
    "Nave larga",
    "Bote de remos",
    "Velero",
    "Barco de guerra",
    "Trigo",
    "Harina",
    "Una gallina",
    "Sal",
    "Hierro",
    "Tela",
    "Cobre trozo",
    "Tela de algod&oacute;n",
    "Jengibre",
    "Una cabra",
    "Canela",
    "Pimienta,",
    "Una oveja",
    "Clavo",
    "Un cerdo",
    "Cerveza",
    "Gal&oacute;n",
    "Jarra",
    "Pan,",
    "Queso,",
    "Carne trozo,",
    "Vino Com&uacute;n (botella)",
    "Vino Excelente (botella)",
    "Una mano de goblin momificada",
    "Un trozo de cristal que brilla d&eacute;bilmente bajo la luna",
    "Una moneda de oro acu&ntilde;ada en una tierra desconocida",
    "Un diario escrito en un idioma que no conoces",
    "Un anillo de lat&oacute;n que nunca se deslustra",
    "Un vieja pieza de ajedrez fabricada con cristal",
    "Un par de dados de hueso, con un s&iacute;mbolo de una calavera en el 6",
    "Un peque&ntilde;o &iacute;dolo que representa a una criatura de pesadilla (provoca pesadillas al portador)",
    "Un collar de cuerda del que cuelgan cuatro dedos de &eacute;lfos momificados",
    "La escritura de una parcela de tierra en un reino desconocido para ti",
    "Un bloque de una onza de peso de un material desconocido",
    "Un reloj de pulsera ensartado con agujas",
    "El diente de una bestia desconocida",
    "Una escama enorme, tal vez de un drag&oacute;n",
    "Una pluma verde y brillante",
    "Una vieja carta de adivinaci&oacute;n que guarda cierto parecido a ti",
    "Un orbe de cristal relleno de humo en movimiento",
    "Un huevo de una onza de peso (30 gramos) con una c&aacute;scara roja y brillante",
    "Una pipa que hace pompas",
    "Un bote de cristal que contiene un extra&ntilde;o pedazo de carne flotando en l&iacute;quido de encurtido",
    "Una peque&ntilde;a caja de m&uacute;sica de manufactura gn&oacute;mica en la que suena una canci&oacute;n que recuerdas vagamente de tu ni&ntilde;ez",
    "Una peque&ntilde;a estatuilla de madera de un halfling engre&iacute;do",
    "Un orbe de lat&oacute;n grabado con extra&ntilde;as runas",
    "Un disco de piedra multicolor",
    "Un diminuto icono de plata de un cuervo",
    "Una bolsa que contiene 47 dientes humanoides, uno de ellos con caries",
    "Un fragmento de obsidiana que siempre est&aacute; caliente al tacto",
    "Una huesuda garra de un drag&oacute;n que cuelga de un collar de cuero liso",
    "Un par de calcetines viejos Baratija",
    "Un libro en blanco cuyas p&aacute;ginas se niegan a ser escritas con tinta, tiza, grafito, o cualquier otra sustancia o marca",
    "Una insignia de plata en forma de estrella de cinco puntas",
    "Un cuchillo que perteneci&oacute; a un familiar",
    "Un vial de cristal repleto de u&ntilde;as cortadas",
    "Un dispositivo rectangular de metal, con dos diminutas tazas met&aacute;licas a cada lado que lanzan chispas cuando se mojan",
    "Un guante blanco de lentejuelas de tama&ntilde;o humano",
    "Un chaleco con cien diminutos agujeros",
    "Un peque&ntilde;o e ingr&aacute;vido bloque de piedra",
    "Un peque&ntilde;o retrato de un goblin",
    "Un vial de cristal vac&iacute;o que huele a perfume cuando se abre",
    "Una piedra preciosa que parece un trozo de carb&oacute;n cuando es examinada por cualquiera menos tu",
    "Un pedacito de tela de una vieja bandera",
    "Una insignia de rango de un legionario perdido",
    "Una peque&ntilde;a campana de plata sin badajo",
    "Un canario mec&aacute;nico dentro de una l&aacute;mpara de manufactura gn&oacute;mica",
    "Una diminuta talla esculpida para que parezca que hay numerosos pies en la parte inferior",
    "Un duende muerto dentro de una di&aacute;fana botella de cristal",
    "Un bote de metal que no ha sido abierto, pero que suena como si estuviera relleno de l&iacute;quido, arena, ara&ntilde;as o cristales rotos (a tu elecci&oacute;n)",
    "Un orbe de cristal lleno de agua, dentro del cual hay un pez de colores que nada con la precisi&oacute;n de un reloj",
    "Una cuchara de plata con una M grabada en el mango",
    "Un silbato fabricado con madera de color dorado",
    "Un escarabajo muerto del tama&ntilde;o de tu mano",
    "Dos soldados de juguete, uno de ellos sin cabeza",
    "Una cajita llena con botones de diferentes tama&ntilde;os",
    "Una vela que no puede dar luz",
    "Una peque&ntilde;a jaula sin puerta",
    "Una vieja llave",
    "Un mapa del tesoro indescifrable",
    "La empu&ntilde;adura de una espada rota",
    "Una pata de conejo",
    "Un ojo de cristal",
    "Un cameo tallado que representa a una persona horrible",
    "Un cr&aacute;neo de plata del tama&ntilde;o de una moneda",
    "Una m&aacute;scara de alabastro",
    "Una pir&aacute;mide de pegajoso incienso que huele muy mal",
    "Un gorro de dormir que, cuando lo llevas puesto, produce agradables sue&ntilde;os",
    "Una &uacute;nica tachuela hecha de hueso La montura de un mon&oacute;culo de oro sin lente",
    "Un cubo de una pulgada (2,54 cent&iacute;metros), con cada cara pintada con un color diferente",
    "Un tirador de puerta de cristal",
    "Un peque&ntilde;a bolsa llena de polvo rosa",
    "El fragmento de una bella canci&oacute;n, escrita con notas musicales en dos trozos de pergamino",
    "Un pendiente de plata en forma de l&aacute;grima fabricado con una aut&eacute;ntica l&aacute;grima",
    "La c&aacute;scara de un huevo pintada con escenas de miseria humana realizadas con inquietante detalle",
    "Un abanico que, al ser desplegado, muestra un gato dormido",
    "Una colecci&oacute;n de pipas de hueso",
    "Un tr&eacute;bol de cuatro hojas prensado dentro de un libro que trata de modales y etiqueta",
    "Una hoja de pergamino en la que hay dibujado un complejo artilugio mec&aacute;nico",
    "Una vaina muy ornamentada que no se ajusta a ninguna espada que hayas encontrado hasta ahora",
    "Una invitaci&oacute;n a una fiesta donde se cometi&oacute; un asesinato",
    "Un pent&aacute;culo de bronce con la cabeza de una rata grabada en su centro",
    "Un pa&ntilde;uelo p&uacute;rpura bordado con el nombre de un poderoso Archimago",
    "La mitad de un plano de un templo, castillo o alguna otra estructura",
    "Un trozo de tela plegada, que al ser desenrollada, se convierte en una estilosa gorra",
    "El recibo del dep&oacute;sito de un banco situado en una ciudad remota",
    "Un diario al que le faltan siete p&aacute;ginas",
    "Una tabaquera de plata vac&iacute;a con una inscripci&oacute;n en su base que dice: “sue&ntilde;os”",
    "Un s&iacute;mbolo sagrado de hierro de un dios desconocido",
    "Un libro que cuenta el alzamiento y la ca&iacute;da de un legendario h&eacute;roe, al que le falta el &uacute;ltimo cap&iacute;tulo",
    "Un vial con sangre de drag&oacute;n",
    "Una antigua flecha &eacute;lfica",
    "Una aguja que nunca se dobla",
    "Un ornamentado broche enano",
    "Una botella de vino vac&iacute;a con una bonita etiqueta que dice: El Mago de las Bodegas, Drag&oacute;n Rojo Aplastante, 331422-W",
    "Un mosaico de azulejo con la superficie acristalada y multicolor",
    "Un rat&oacute;n petrificado",
    "Una bandera pirata con un cr&aacute;neo de drag&oacute;n y dos tibias cruzadas",
    "Un diminuto cangrejo o ara&ntilde;a mec&aacute;nica que solo se mueve cuando nadie la observa",
    "Un frasco de manteca con una etiqueta que dice: Grasa de Grifo",
    "Una caja de madera con un fondo de cer&aacute;mica en el que hay un gusano con una cabeza en cada extremo de su cuerpo",
    "Una urna met&aacute;lica que contiene las cenizas de un h&eacute;roe",
]; //let COSAS = [




function print_cosas(element_id) {
    var element = document.getElementById(element_id);
    if (!element) return;

    var html_code = "";
    let cosa_text;

    for (let i=0; i<3; i++) {
        cosa_text = random_from_list(COSAS);

        if (i > 0) {
            html_code += '<br/>';
        } //if (i > 0) {

        html_code += print_fortune_cookie(cosa_text);
    }; //for (let i=0; i<3; i++) {

    element.innerHTML = html_code;
    element.scrollTop = "0";
} //function print_cosas(element_id)
