const EMOJIS = [
    "Airplane.png",
    "Angry face.png",
    "Anguished face.png",
    "Anxious face with sweat.png",
    "Astonished face.png",
    "Avocado.png",
    "Backhand index pointing down.png",
    "Backhand index pointing left.png",
    "Backhand index pointing right.png",
    "Backhand index pointing up.png",
    "Baltasar.png",
    "Banana.png",
    "Beach with umbrella.png",
    "Beach.png",
    "Beaming face with smiling eyes.png",
    "Bell.png",
    "Bicycle.png",
    "Broken heart.png",
    "Bubbles.png",
    "Calendar.png",
    "Call me hand.png",
    "Camera.png",
    "Cat.png",
    "Check mark.png",
    "Clapping hands.png",
    "Clock.png",
    "Clown face.png",
    "Cold face.png",
    "Compass.png",
    "Confounded face.png",
    "Cool.png",
    "Cowboy hat face.png",
    "Crossed fingers.png",
    "Crying face.png",
    "Crystal ball.png",
    "Dissapointed face.png",
    "Dizzy face.png",
    "Dog.png",
    "Downcast face with sweat.png",
    "Drooling face.png",
    "Eggplant.png",
    "Envelope.png",
    "Exploding head.png",
    "Expressioless face.png",
    "Face blowing a kiss.png",
    "Face savoring food.png",
    "Face screaming in fear.png",
    "Face with hand over mouth.png",
    "Face with head-bandage.png",
    "Face with medical mask.png",
    "Face with monocle.png",
    "Face with open mouth.png",
    "Face with raised eyebrow.png",
    "Face with rolling eyes.png",
    "Face with steam from nose.png",
    "Face with symbols on mouth.png",
    "Face with tears of joy.png",
    "Face with thermometer.png",
    "Face with tongue.png",
    "Face without mouth.png",
    "Fearful face.png",
    "Fire.png",
    "Flushed face.png",
    "Folded hands.png",
    "Free.png",
    "Frowning face with open mouth.png",
    "Frowning face.png",
    "Gaspar.png",
    "Gemstone.png",
    "Glasses.png",
    "Green apple.png",
    "Grimacing face.png",
    "Grinning face with big eyes.png",
    "Grinning face with sweat.png",
    "Grinning face-1.png",
    "Grinning face.png",
    "Grinning squinting face.png",
    "Group.png",
    "Hamburger.png",
    "Hand with fingers splayed.png",
    "Handshake.png",
    "Heart.png",
    "High voltage.png",
    "Hot face.png",
    "House.png",
    "Hugging face.png",
    "Hushed face.png",
    "Index pointing up.png",
    "Joker.png",
    "Kissing face with closed eyes.png",
    "Kissing face with smiling eyes.png",
    "Kissing face.png",
    "Kiwi.png",
    "Landmark.png",
    "Left facing fist.png",
    "Lion.png",
    "Loudly crying face.png",
    "Love you gesture.png",
    "Lying face.png",
    "Mailbox.png",
    "Melchor.png",
    "Middle finger.png",
    "Money mouth face $.png",
    "Money mouth face £.png",
    "Money mouth face ¥.png",
    "Money mouth face &euro;.png",
    "Money mouth face ₽.png",
    "Money mouth face bitcoin.png",
    "Monkey.png",
    "Nauseated face.png",
    "Nerd face.png",
    "Neutral face.png",
    "Ok hand.png",
    "Ok.png",
    "Oncoming fist.png",
    "Open hands.png",
    "Palm.png",
    "Palms up together.png",
    "Panda.png",
    "Party popper.png",
    "Partying face.png",
    "Peach.png",
    "Pencil.png",
    "Pensive face.png",
    "Pile of poo.png",
    "Pinch hand.png",
    "Pinched fingers.png",
    "Pizza.png",
    "Pleading face.png",
    "Pouting face.png",
    "Rainbow.png",
    "Raised back of hand.png",
    "Raised fist.png",
    "Raised hand.png",
    "Raising hands.png",
    "Recycling symbol.png",
    "Red apple.png",
    "Relieved face.png",
    "Right facing fist.png",
    "Robot.png",
    "Rocket.png",
    "Rolling on the floor laughing.png",
    "Round pushpin.png",
    "Sad but relieved face.png",
    "Santa Claus.png",
    "Scrunched face.png",
    "Shushing face.png",
    "Sign of the horns.png",
    "Sleep face.png",
    "Sleepy face.png",
    "Slightly frowning face.png",
    "Slightly smiling face.png",
    "Smiling face with halo.png",
    "Smiling face with heart-eyes.png",
    "Smiling face with hearts.png",
    "Smiling face with smiling eyes.png",
    "Smiling face with sunglasses.png",
    "Smiling face.png",
    "Smirking face.png",
    "Sneezing face.png",
    "Sparkles.png",
    "Squinting face with tongue.png",
    "Star.png",
    "Star-struck.png",
    "Sweat droplets.png",
    "Thinking face.png",
    "Thumbs down.png",
    "Thumbs up.png",
    "Tired face.png",
    "Umbrella with rain drops.png",
    "Unamused face.png",
    "Unicorn.png",
    "Upside-down face.png",
    "Victory hand.png",
    "Vomiting face.png",
    "Vulcan salute.png",
    "Waving hand.png",
    "Weary face.png",
    "Weather.png",
    "Winking face with tongue.png",
    "Winking face.png",
    "Woozy face.png",
    "Worried face-1.png",
    "Worried face.png",
    "Writing hand.png",
    "Xmas ball.png",
    "Xmas tree.png",
    "Yawning face.png",
    "Zany face.png",
    "Zipper-mouth face.png",
]; //const EMOJIS = [
