var IRONSWORN = [
    "Intrigar%0ARiesgo%0AForzar Rendici&oacute;n%0AEs una Distracci&oacute;n",
    "Contraatacar%0ACapacidad%0ACoord. Con aliados%0AEs una Distracci&oacute;n",
    "Debilitar%0APrecio%0AReunir Refuerzos%0AEs una Distracci&oacute;n",
    "Iniciar%0AAliada%0AAprovecharse%0AEs una Distracci&oacute;n",
    "Crear%0ABatalla%0AImprudencia%0AEs una Distracci&oacute;n",
    "Jurar%0ASeguridad%0AIntimidar%0ASecreto oscuro",
    "Vengar%0ASupervivencia%0ARevelar sorpresa%0ASecreto oscuro",
    "Vigilar%0AArma%0ADirigir atenci&oacute;n a%0ASecreto oscuro",
    "Derrotar%0AHerida%0ADestruir o Inutilizar%0ASecreto oscuro",
    "Controlar%0AAlbergue%0AAcci&oacute;n Decisiva%0ASecreto oscuro",
    "Romper%0AL&iacute;der%0AAcci&oacute;n Decisiva%0ATrampa",
    "Arriesgar%0AMiedo%0AForzar Rendici&oacute;n%0ATrampa",
    "Rendir%0ATiempo%0ACoord. Con aliados%0ATrampa",
    "Inspeccionar%0ADeber%0AReunir Refuerzos%0ATrampa",
    "Incursionar%0ASecreto%0AAprovecharse%0ATrampa",
    "Evadir%0AInocencia%0AImprudencia%0ASuposici&oacute;n falsa",
    "Agredir%0ARenombre%0AIntimidar%0ASuposici&oacute;n falsa",
    "Desviar%0ADirecci&oacute;n%0ARevelar sorpresa%0ASuposici&oacute;n falsa",
    "Amenazar%0AMuerte%0ADirigir atenci&oacute;n a%0ASuposici&oacute;n falsa",
    "Atacar%0AHonor%0ADestruir o Inutilizar%0ASuposici&oacute;n falsa",
    "Dejar%0ATrabajo%0ADestruir o Inutilizar%0AAlianza secreta",
    "Preservar%0ASoluci&oacute;n%0AAcci&oacute;n Decisiva%0AAlianza secreta",
    "Manipular%0AHerramienta%0AForzar Rendici&oacute;n%0AAlianza secreta",
    "Remover%0AEquilibrio%0ACoord. Con aliados%0AAlianza secreta",
    "Eliminar%0AAmor%0AReunir Refuerzos%0AAlianza secreta",
    "Retirar%0ABarrera%0AAprovecharse%0ABeneficia enemigo",
    "Abandonar%0ACreaci&oacute;n%0AImprudencia%0ABeneficia enemigo",
    "Investigar%0APodredumbre%0AIntimidar%0ABeneficia enemigo",
    "Retener%0AComercio%0ARevelar sorpresa%0ABeneficia enemigo",
    "Concentrar%0AV&iacute;nculo%0ADirigir atenci&oacute;n a%0ABeneficia enemigo",
    "Destapar%0AEsperanza%0ADirigir atenci&oacute;n a%0ARetorno inesperado",
    "Infringir%0ASuperstici&oacute;n%0ADestruir o Inutilizar%0ARetorno inesperado",
    "Auxiliar%0APaz%0AAcci&oacute;n Decisiva%0ARetorno inesperado",
    "Apoyar%0AEnga&ntilde;o%0AReforzar Defensa%0ARetorno inesperado",
    "Titubear%0AHistoria%0APreparar acci&oacute;n%0ARetorno inesperado",
    "Reprimir%0AMundo%0AVentaja del terreno%0ANuevo Enemigo",
    "Cazar%0AJuramento%0AAprovecharse%0ANuevo Enemigo",
    "Compartir%0AProtecci&oacute;n%0AImprudencia%0ANuevo Enemigo",
    "Destruir%0ANaturaleza%0AIntimidar%0ANuevo Enemigo",
    "Evitar%0AOpini&oacute;n%0ARevelar sorpresa%0ANuevo Enemigo",
    "Rechazar%0ACarga%0AArma o Habilidad%0AObjetivo com&uacute;n",
    "Pedir%0AVenganza%0ACrear Oportunidad%0AObjetivo com&uacute;n",
    "Explorar%0AOportunidad%0AAtaque preciso%0AObjetivo com&uacute;n",
    "Reforzar%0AFacci&oacute;n%0AAcci&oacute;n Decisiva%0AObjetivo com&uacute;n",
    "Aprovechar%0APeligro%0AReforzar Defensa%0AObjetivo com&uacute;n",
    "Lamentar%0ACorrupci&oacute;n%0APreparar acci&oacute;n%0AIdentidad secreta",
    "Revelar%0ALibertad%0AVentaja del terreno%0AIdentidad secreta",
    "Reunir%0ADeuda%0ACrear Oportunidad%0AIdentidad secreta",
    "Desafiar%0AOdio%0AAtaque preciso%0AIdentidad secreta",
    "Transformar%0APosesi&oacute;n%0AAtaque Poderoso%0AIdentidad secreta",
    "Perseverar%0AExtra&ntilde;o%0AAtaque preciso%0ATraicionado",
    "Servir%0APaso%0AArma o Habilidad%0ATraicionado",
    "Comenzar%0ATierra%0ACrear Oportunidad%0ATraicionado",
    "Mover%0ACriatura%0AAtaque preciso%0ATraicionado",
    "Coordinar%0AEnfermedad%0AAcci&oacute;n Decisiva%0ATraicionado",
    "Resistir%0AVentaja%0AReforzar Defensa%0ALlegas muy tarde",
    "Esperar%0ASangre%0APreparar acci&oacute;n%0ALlegas muy tarde",
    "Impresionar%0AIdioma%0AVentaja del terreno%0ALlegas muy tarde",
    "Agarrar%0ARumor%0ACrear Oportunidad%0ALlegas muy tarde",
    "Oponer%0ADebilidad%0AAtaque Poderoso%0ALlegas muy tarde",
    "Capturar%0ACodicia%0AAtaque Poderoso%0ASe revela enemigo",
    "Aplastar%0AFamilia%0ACrear Oportunidad%0ASe revela enemigo",
    "Retar%0ARecurso%0AArma o Habilidad%0ASe revela enemigo",
    "Adquirir%0AEstructura%0ACrear Oportunidad%0ASe revela enemigo",
    "Salvaguardar%0ASue&ntilde;o%0AAtaque preciso%0ASe revela enemigo",
    "Terminar%0AComunidad%0AAtaque preciso%0A+Enemigos",
    "Fortalecer%0AGuerra%0AReforzar Defensa%0A+Enemigos",
    "Restaurar%0APresagio%0APreparar acci&oacute;n%0A+Enemigos",
    "Mejorar%0APremio%0AVentaja del terreno%0A+Enemigos",
    "Mandar%0ADestino%0AAtaque Poderoso%0A+Enemigos",
    "Negar%0AImpulso%0AAtaque preciso%0ANuevo peligro",
    "Encontrar%0APoder%0AAtaque preciso%0ANuevo peligro",
    "Entregar%0AMemoria%0ACrear Oportunidad%0ANuevo peligro",
    "Esconder%0ARuina%0AArma o Habilidad%0ANuevo peligro",
    "Fortificar%0AMisticismo%0ACrear Oportunidad%0ANuevo peligro",
    "Delatar%0ARival%0AAtaque preciso%0ADesaparici&oacute;n de",
    "Asegurar%0AProblema%0AAtaque preciso%0ADesaparici&oacute;n de",
    "Llegar%0AIdea%0AReforzar Defensa%0ADesaparici&oacute;n de",
    "Afectar%0ARevancha%0APreparar acci&oacute;n%0ADesaparici&oacute;n de",
    "Cambiar%0ASalud%0AVentaja del terreno%0ADesaparici&oacute;n de",
    "Defender%0ACompa&ntilde;erismo%0AVentaja del terreno%0ACambia relaci&oacute;n",
    "Debatir%0AEnemigo%0AAtaque Poderoso%0ACambia relaci&oacute;n",
    "Respaldar%0AReligi&oacute;n%0AVentaja del terreno%0ACambia relaci&oacute;n",
    "Seguir%0AEsp&iacute;ritu%0AAtaque preciso%0ACambia relaci&oacute;n",
    "Construir%0AFama%0AArma o Habilidad%0ACambia relaci&oacute;n",
    "Localizar%0ADesolaci&oacute;n%0ACrear Oportunidad%0ANuevas conexiones",
    "Soportar%0AFuerza%0AArma o Habilidad%0ANuevas conexiones",
    "Liberar%0AConocimiento%0AAtaque Poderoso%0ANuevas conexiones",
    "Perder%0AVerdad%0AReforzar Defensa%0ANuevas conexiones",
    "Reducir%0AMisi&oacute;n%0APreparar acci&oacute;n%0ANuevas conexiones",
    "Escalar%0AOrgullo%0APreparar acci&oacute;n%0AHab. Inesperadas",
    "Distraer%0AP&eacute;rdida%0AVentaja del terreno%0AHab. Inesperadas",
    "Viajar%0ALey%0AAtaque Poderoso%0AHab. Inesperadas",
    "Escoltar%0ACamino%0AAtaque Poderoso%0AHab. Inesperadas",
    "Aprender%0AAdvertencia%0AAtaque Poderoso%0AHab. Inesperadas",
    "Comunicar%0ARelaci&oacute;n%0AArma o Habilidad%0ATira 2 veces m&aacute;s",
    "Salir%0ARiqueza%0ACrear Oportunidad%0ATira 2 veces m&aacute;s",
    "Buscar%0AHogar%0AArma o Habilidad%0ATira 2 veces m&aacute;s",
    "Cargar%0AEstrategia%0AAtaque Poderoso%0ATira 2 veces m&aacute;s",
    "Convocar%0ASuministro%0AAcci&oacute;n Inesperada%0ATira 2 veces m&aacute;s"
];
