
let DETALLES_LUGARES = [
    "Crujido de tablas",
    "L&aacute;mparas humeantes",
    "Zumbido de luces el&eacute;ctricas",
    "Tictac de relojes",
    "Agua goteando",
    "Fuego avivado",
    "Cortinas pesadas",
    "Alfombras",
    "Tapices",
    "Ventanas",
    "Plantas",
    "Flores",
    "Ilustraciones",
    "Alfombra",
    "Polvo",
    "Detritus",
    "Da&ntilde;o",
    "Desgaste",
    "Gruesa",
    "Ra&iacute;do",
    "Mobiliario",
    "Galas",
    "Lujoso",
    "Tejido",
    "Espartano",
    "Andrajoso",
    "Funcional",
    "Elegantes",
    "C&oacute;modo",
    "Austero",
    "Escaleras",
    "Puertas circulares",
    "Pasarelas",
    "Claraboyas",
    "Balc&oacute;n",
    "Bodega",
    "Puertas secretas",
    "Escalerillas",
    "Firme",
    "Acogedor",
    "Abovedado",
    "Bajo",
    "Raqu&iacute;tico",
    "Ventilado",
    "Fr&iacute;o",
    "C&aacute;lido",
    "Espacioso",
    "Destartalado",
    "Protecciones",
    "Revoltijo",
    "Dispositivos",
    "Artefactos",
    "Muebles",
    "Santuario",
    "Extra&ntilde;os",
    "Ins&oacute;litos",
    "Runas",
    "Antiguos",
    "Altar",
]; //let DETALLES_LUGARES = [


let LUGARES_SOMBRAS_URBANAS = [
    "Un solar de construcci&oacute;n abandonado",
    "El despacho de un abogado de dudosa reputaci&oacute;n",
    "Una plaza de la ciudad con una majestuosa fuente",
    "Un puente que est&aacute; pidiendo a gritos que lo reparen",
    "Un oscuro cruce iluminado por una farola que no deja de zumbar",
    "Un estadio deportivo en silencio",
    "Un callej&oacute;n entre dos tiendas cerradas",
    "Un silencioso and&eacute;n del metro",
    "El &aacute;tico de un brillante rascacielos",
    "Un cementerio de la ciudad olvidado hace mucho tiempo",
    "El aparcamiento de un vendedor de coches de poca monta",
    "Una discoteca de m&uacute;sica machacona",
    "Un mercado agr&iacute;cola",
    "Un cochambroso bar de rock",
    "Un restaurante de mala muerte casi a las afueras de la ciudad",
    "Un sendero de un parque p&uacute;blico por el que la gente sale a correr",
    "Un almac&eacute;n lleno hasta los topes de env&iacute;os internacionales",
    "Una ajetreada calle del centro un viernes por la noche",
    "Un callej&oacute;n lleno de basura e inmundicia",
    "El tejado de una casa de ladrillo con las puertas y ventanas tapiadas",
    "La amplia escalinata de un juzgado de la ciudad",
    "La biblioteca del centro al amanecer",
    "Una bulliciosa estaci&oacute;n de tren",
    "El s&oacute;tano lleno de tuber&iacute;as de un complejo industrial",
    "Una sala de urgencias con falta de presupuesto",
    "Una pista de baloncesto en mitad de la ciudad",
    "Un centro c&iacute;vico sumido en un mar de desesperaci&oacute;n",
    "Antro",
    "Barrac&oacute;n",
    "Or&aacute;culo",
    "Posada",
    "Taberna",
    "Sala de juegos",
    "Burdel de drogas",
    "Mercado",
    "Taller",
    "Panader&iacute;a",
    "Carnicer&iacute;a",
    "Forja",
    "Sastrer&iacute;a",
    "Casa",
    "Establos",
    "F&aacute;brica",
    "Puesto de guardia",
    "Juzgado",
    "C&aacute;rcel",
    "Muelle",
    "Cuadra",
    "Cabras",
    "Cerveza",
    "Viviendas",
    "Ruinas",
    "Apartamentos",
    "Casa",
    "Casa de ba&ntilde;os",
    "Plaza",
    "Santuario",
    "Tatuajes",
    "M&eacute;dico",
    "Re&ntilde;ideros",
    "Gruta",
    "Fuente",
    "Almac&eacute;n",
    "Corrales",
    "F&aacute;brica",
    "Refiner&iacute;a",
    "Anguilera",
    "Jard&iacute;n de setas",
    "Mercado",
    "Restaurante",
    "Bar",
    "Academia",
    "Sal&oacute;n",
    "Caf&eacute;",
    "Florister&iacute;a",
    "Estanco",
    "Librer&iacute;a",
    "Joyer&iacute;a",
    "Sastrer&iacute;a",
    "Galer&iacute;a",
    "Establos",
    "Cobertizo",
    "Botica",
    "Destiler&iacute;a",
    "Vinater&iacute;a",
    "Caballos",
    "Artesan&iacute;a",
    "Edificio",
    "Viviendas",
    "Pantal&aacute;n de barcas",
    "Teatro",
    "&Oacute;pera",
    "Mansi&oacute;n",
    "Villa",
    "Adosados",
    "Puesto",
    "Cl&iacute;nica",
    "Templo",
    "Cisterna",
    "Parque",
    "Monumento",
    "Guardia",
    "Planta",
    "Mercado",
    "Jard&iacute;n",
    "Archivo",
    "Espiritualista",
    "Banco",
    "Alquimista",
    "El Club de los Falsificadores",
    "Los Narradores de Historias",
    "El &Aacute;ngel Gris",
    "Bar del Infierno",
    "La Sociedad de los Trabajos Dif&iacute;ciles",
    "Los Reveladores de Secretos",
    "Arrabal",
    "Burdel",
    "Conventillo",
    "Taura",
    "Tugurio",
    "Un bar",
    "Org&iacute;a",
    "El subterr&aacute;neo",
    "Montes Encantados",
    "Un sal&oacute;n de baile",
    "Carnavales",
    "Un feroz Drakon",
    "Un amuleto perdido",
    "Las escarpadas monta&ntilde;as de Mylantha",
    "Las cuevas m&aacute;s all&aacute; de la frontera",
    "Un nido de serpientes moradas",
    "Las tormentas el&eacute;ctricas son tempranas esta temporada",
    "Rastros de una pelea reciente en la arena",
    "Historias compartidas alrededor del fuego",
    "Los cazadores de bestias se acercan a Milo",
    "Un posadero gecko",
    "El cristal",
    "La polilla tiene un mensaje",
    "Se siente el campo de energ&iacute;a de una reliquia",
    "Una audiencia con el p&aacute;jaro arco&iacute;ris",
    "Un posible heredero al trono",
    "El puente de hueso en un atardecer ventoso",
    "El esp&iacute;a de Korlax golpea a Olara, la bruja hundida",
    "Un comerciante trae un regalo",
    "Se convoca al Consejo de Reptiles",
    "El Cinder Knight se interpone en tu camino",
    "La casa de t&eacute; en la copa del &aacute;rbol",
    "El bosque susurrante",
    "La br&uacute;jula maldita",
    "Un presagio entre las estrellas",
    "Una torre de m&aacute;rmol en el horizonte",
    "Coral, la cobra Prima del rey",
    "Una antigua escritura desaf&iacute;a las creencias",
    "El sauce solitario",
    "Las profundidades del Valle de las Perlas",
    "La batalla de Quaruna",
    "Hermanos en fuga",
    "El r&iacute;o estrecho guarda un secreto",
    "La profec&iacute;a de Sul-Mahat",
    "Enigm&aacute;tica puerta tallada",
    "Una flor, un libro y un duelo",
    "El orbe en las ruinas atrapadas de un observatorio",
]; //let LUGARES_SOMBRAS_URBANAS = [

let LUGARES_PARAMOS_AVENTURADOS = [
    "Arenas",
    "Bah&iacute;a",
    "Baj&iacute;o",
    "Bosque",
    "Brezal",
    "Canal",
    "Ca&ntilde;ada",
    "Ca&ntilde;on",
    "Cerros",
    "Ci&eacute;naga",
    "Colinas",
    "Cumbres",
    "Desierto",
    "Dunas",
    "Erial",
    "Escarpe",
    "Estepa",
    "Fangal",
    "Fosa",
    "Mercado",
    "Franja",
    "Iceberg",
    "Jungla",
    "Ladera",
    "Lago",
    "Lamedal",
    "Llanos",
    "Llanuras",
    "Mar",
    "Marca",
    "Marisma",
    "Marjal",
    "Matorral",
    "Meseta",
    "Monta&ntilde;a",
    "Monte",
    "Muro",
    "Pantano",
    "Paraje",
    "P&aacute;ramo",
    "Picos",
    "Pradera",
    "Prado",
    "Risco",
    "Rivera",
    "Sabana",
    "Sierra",
    "Soto",
    "Soto",
    "Valle",
    "Yermo",
    "Abismo",
    "Cavernas",
    "Agujero",
    "alc&aacute;zar",
    "Aldea",
    "Anillo",
    "&Aacute;rbol",
    "Arroyo",
    "Barrera",
    "Bosque",
    "Caba&ntilde;a",
    "Caldero",
    "Camino",
    "Campo",
    "Capilla",
    "Cascada",
    "Ci&eacute;naga",
    "C&iacute;rculo",
    "Ciudad",
    "Ciudad",
    "Colina",
    "Cr&aacute;ter",
    "Cresta",
    "Cripta",
    "Cruce",
    "Cubil",
    "Cuesta",
    "Cueva",
    "Espira",
    "Foso",
    "Fuerte",
    "Lago",
    "Monta&ntilde;a",
    "Muro",
    "Paso",
    "Piedra",
    "Playa",
    "Prado",
    "Puerta",
    "Puesto",
    "Refugio",
    "Roca",
    "Ruina",
    "Templo",
    "Torre",
    "Trono",
    "Tumba",
    "Valla",
    "Valle",
    "Zanja",
    "Zarzal",
    "Cavernas",
    "Nubes",
    "Tierra",
    "Terremotos",
    "Niebla",
    "G&eacute;iseres",
    "Colinas",
    "Lagos",
    "Rel&aacute;mpagos",
    "Lluvia",
    "R&iacute;os",
    "Mares",
    "Estaciones",
    "Costas",
    "Cielo",
    "Estrellas",
    "Tormentas",
    "Truenos",
    "Mareas",
    "Viento",
]; //let LUGARES_PARAMOS_AVENTURADOS = [



let LUGARES_PARAMOS_AVENTURADOS_ADJETIVO = [
    "Yermo",
    "Abrupto",
    "Amarillo",
    "Ardiente",
    "Ardiente",
    "&Aacute;rido",
    "Azul",
    "Bendito",
    "Blanco",
    "Borroso",
    "Brillante",
    "Brumoso",
    "Ca&iacute;do",
    "Clara",
    "Doradas",
    "Eterno",
    "Fragoso",
    "Fr&iacute;o",
    "Funesto",
    "Furtivo",
    "Helado",
    "Infinito",
    "Inquieto",
    "Largo",
    "Lejano",
    "Letal",
    "Maldito",
    "Malvado",
    "Marchito",
    "Mortal",
    "Muerto",
    "Negro",
    "Olvidado",
    "Oscuro",
    "Pardo",
    "Peligroso",
    "P&eacute;trea",
    "Plateado",
    "P&uacute;rpura",
    "Rajada",
    "Regio",
    "Rojizo",
    "Rojo",
    "Roto",
    "Sagrado",
    "Salvaje",
    "Sombr&iacute;o",
    "Temible",
    "Triste",
    "Verde",
    "Agudo",
    "Ajado",
    "Alto",
    "Antiguo",
    "Ardiente",
    "Aullante",
    "Azul",
    "Bajo",
    "Blanco",
    "Brillante",
    "Ca&iacute;do",
    "Cercano",
    "Cobrizo",
    "Dentado",
    "Dorado",
    "Eterno",
    "Flotante",
    "Helado",
    "Hierro",
    "Hundido",
    "Ilustre",
    "Inmundo",
    "Irreal",
    "Leal",
    "Lejano",
    "Majado",
    "Maldito",
    "Maligno",
    "Muerto",
    "Nefando",
    "Negro",
    "Nublado",
    "Oculto",
    "Oscuro",
    "Pardo",
    "Partido",
    "Perdido",
    "Plateado",
    "Rocoso",
    "Roja",
    "Roto",
    "Salvaje",
    "Sinuoso",
    "Solitario",
    "Sombr&iacute;o",
    "Temible",
    "Terrible",
    "Turulato",
    "Velado",
    "Voluble"
]; //let LUGARES_PARAMOS_AVENTURADOS_ADJETIVO = [



let LUGARES_PARAMOS_AVENTURADOS_NOMBRE = [
    "Bruja",
    "Calavera",
    "Ceniza",
    "Cielo",
    "Demonio",
    "Desesperaci&oacute;n",
    "Desolaci&oacute;n",
    "Destino",
    "Dios",
    "Drag&oacute;n",
    "Esperanza",
    "Espina",
    "Fantasma",
    "Fuego",
    "Furia",
    "Gigante",
    "Honor",
    "Horror",
    "Hueso",
    "Humo",
    "Infierno",
    "Lluvia",
    "Luz",
    "Maldici&oacute;n",
    "Miedo",
    "Muerte",
    "Muerto",
    "Niebla",
    "Oro",
    "Oscuridad",
    "Para&iacute;so",
    "Peligro",
    "Pesadumbre",
    "Plata",
    "Refugio",
    "Reina",
    "Rey",
    "Salvador",
    "Se&ntilde;or",
    "Serpiente",
    "Sol",
    "Sombra",
    "Tormenta",
    "Traidor",
    "Tristeza",
    "Trol",
    "Trueno",
    "Victoria",
    "Vida",
    "Agua",
    "Almas",
    "Barro",
    "Brazo",
    "Bruja",
    "Caballero",
    "Cabeza",
    "Cad&aacute;ver",
    "Calavera",
    "Ceniza",
    "Coraz&oacute;n",
    "Cristal",
    "Daga",
    "Dedo",
    "Demonio",
    "Diablo",
    "Dios",
    "Espada",
    "Esperanza",
    "Esp&iacute;ritu",
    "Fango",
    "Fantasma",
    "Fuego",
    "Gigante",
    "Goblin",
    "Guerrero",
    "H&eacute;roe",
    "Holl&iacute;n",
    "Humo",
    "Ladr&oacute;n",
    "Lanza",
    "Mago",
    "Maldici&oacute;n",
    "Mano",
    "Marinero",
    "Miedo",
    "Muerte",
    "Ni&ntilde;o",
    "Ojo",
    "Oro",
    "Pie",
    "Piedra",
    "Plata",
    "Reina",
    "Rey",
    "Sacerdote",
    "Sangre",
    "Trol",
    "Villano"
]; //let LUGARES_PARAMOS_AVENTURADOS_NOMBRE = [


let LUGARES_PARAMOS_AVENTURADOS_ASENTAMIENTO = [
    "Aldott<br/>(Bendito)",
    "Almahid<br/>(Puente Manzano)",
    "Elesett<br/>(Los Ca&iacute;dos)",
    "Feketz<br/>(Rocanegra)",
    "Godor<br/>(Pozo)",
    "Kelegaz<br/>(Vadoeste)",
    "Kigyov<br/>(Pantano Serpentino)",
    "Kiralokas<br/>(Castillo Real)",
    "Kiralsir<br/>(Tumba Real)",
    "Magziklar<br/>(Risco Alto)",
    "Mocsar<br/>(Ci&eacute;naga)",
    "Nagyvros<br/>(Villarriba)",
    "Okorm<br/>(Campo de Bueyes)",
    "Orkfall<br/>(Muro de orcos)",
    "Perov<br/>(Aguas Rojas)",
    "Soterdo<br/>(Bosque Oscuro)",
    "Tehenvar(Ciudad Bovina)",
    "Toron<br/>(Torre&oacute;n)",
    "Torott<br/>(Fuerte Hierro)",
    "Utolszer<br/>(&uacute;ltimo Basti&oacute;n)",
    "Valavolg<br/>(Valle Verde)",
    "Vastar<br/>(Guardia Enana)",
    "Viz<br/>(Campo de Bueyes)",
    "Volgyom<br/>(Valle)",
    "Zoldom<br/>(Colina Verde)",
    "Asalu Ilu<br/>(Urbe del Desierto)",
    "Atijo Ina<br/>(Llama Anciana)",
    "Bajesia<br/>(Estandarte Roto)",
    "Dudu Olomi<br/>(R&iacute;o Negro)",
    "Ebutte Meta<br/>(Tres Puertos)",
    "Ejodo<br/>(Pantano Serpiente)",
    "Esukale<br/>(Cena del Diablo)",
    "Fadormi<br/>(Brote Plateado)",
    "Funfumi<br/>(Aguasblancas)",
    "Guluna<br/>(V&iacute;a &Aacute;urea)",
    "Ijisofo<br/>(Valle del Tormento)",
    "Ikukenu<br/>(Puerta Carest&iacute;a)",
    "Iwin Ago<br/>(Guardia Fe&eacute;rica)",
    "Jinibi<br/>(Lugar Remoto)",
    "Oba Ile<br/>(Hogar del Rey)",
    "Oduroke<br/>(Colina de Oraci&oacute;n)",
    "Ogbinibi<br/>(Lugar de Cultivo)",
    "Ogunibi<br/>(Lugar de Batalla)",
    "Okanigi<br/>(&Aacute;rbol &Uacute;nico)",
    "Okutasi<br/>(Grabador de Rocas)",
    "Olusaki<br/>(Fortaleza del Mago)",
    "Oluwaka<br/>(Tumba del Se&ntilde;or)",
    "Opolokuta<br/>(Rocas-mil)",
    "Opoligi<br/>(&Aacute;rboles-sin-fin)",
    "Oporusura<br/>(Tesoro Divino)",
    "Etuvartio<br/>(Puesto Avanzado)",
    "Hopea Kaivos<br/>(Mina de Plata)",
    "Kalapunki<br/>(Pueblo Pesquero)",
    "Kivimurri<br/>(Muro de Piedra)",
    "Maaginen<br/>(Magia)",
    "Maenrinne<br/>(Ladera)",
    "Makinna<br/>(Colina del Castillo)",
    "Merenranta<br/>(Orilla al Mar)",
    "Metsasmaat<br/>(Coto de Caza)",
    "Mustakota<br/>(Choza Negra)",
    "Miekka<br/>(Espada)",
    "Pienni Paikka<br/>(Lugar Bajo)",
    "Pyha Paikka<br/>(Lugar Sacro)",
    "Rantakallio<br/>(Risco)",
    "Rikki<br/>(Quebrada)",
    "Suo<br/>(Ci&eacute;naga)",
    "Suosi<br/>(Privilegiado)",
    "Torni<br/>(Torre)",
    "Turvapaikka<br/>(Refugio)",
    "Uusipunki<br/>(Nueva Ciudad)",
    "Valkoinen Kivi<br/>(Rocablanca)",
    "Valtaistuin<br/>(Trono)",
    "Vapaanki<br/>(Ciudad Libre)",
    "Vihrea Paikka<br/>(Zona Verde)",
    "Viimeinen<br/>(&Uacute;ltimo Hogar)",
    "Airdib<br/>(Aguas Benditas)",
    "Airjinh<br/>(Aguasclaras)",
    "Akhir Jalan<br/>(Fin del Camino)",
    "Berdarah<br/>(Sangriento)",
    "Bidang<br/>(Tierra de Barbecho)",
    "Canbula<br/>(Templo de la Luna)",
    "Ditingga<br/>(Abandonado)",
    "Emasunga<br/>(Arroyo Dorado)",
    "Gunung<br/>(Monta&ntilde;a)",
    "Kayu<br/>(Madera)",
    "Kuil<br/>(Templo)",
    "Ladang Hijau<br/>(Campoverde)",
    "Lembah<br/>(Valle)",
    "Menjau<br/>(Lejano)",
    "Ngarai<br/>(Ca&ntilde;&oacute;n)",
    "Persimpangan<br/>(Encrucijada)",
    "Puncakit<br/>(Cima)",
    "Sungairac<br/>(R&iacute;o Ponzo&ntilde;oso)",
    "Teibing<br/>(Acantilado)",
    "Tempat Aman<br/>(Lugar Seguro)",
    "Tempat Istir<br/>(Lugar de paz)",
    "Terkutuk<br/>(Maldito)",
    "Tersentu<br/>(Tocado por Dios)",
    "Wahah<br/>(Oasis)",
    "Yangtinggi<br/>(Alta Torre)",
]; //let LUGARES_PARAMOS_AVENTURADOS_ASENTAMIENTO = [


let LUGARES_SCRAPS_ADVERBIO = [
    "Poqu&iacute;simo",
    "Poco",
    "",
    "",
    "Muy",
    "Much&iacute;simo"
]; // let LUGARES_SCRAPS_ADVERBIO = [



let LUGARES_SCRAPS_ADJETIVO = [
    "Denso",
    "Ascendente",
    "C&aacute;lido",
    "H&uacute;medo",
    "Antiguo",
    "Diverso",
    "Fauna Diversa",
    "Flora Diversa",
    "Paisajes Diversos",
    "Ruinas Diversas",
]; // let LUGARES_SCRAPS_ADJETIVO = [



function compute_lugares_scraps(numero_de_lugares) {
    let adverbio, adjetivo, last_adjetivo = "";

    let html_text = "";

    for (let i=0; i<numero_de_lugares; i++) {
        adverbio = random_from_list(LUGARES_SCRAPS_ADVERBIO);

        do {
            adjetivo = random_from_list(LUGARES_SCRAPS_ADJETIVO);
        } while(adjetivo == last_adjetivo);

        if (i > 0) {
            html_text += '<br/>';
        } // if (i > 0) {

        html_text += adverbio + " " + adjetivo;
        last_adjetivo = adjetivo;
    } //for (let i=0; i<numero_de_lugares; i++)

    return print_fortune_cookie(html_text);

} //function compute_lugares_scraps(numero_de_lugares)



let PREGUNTAS_LUGAR = [
    "&iquest;Qu&eacute; hay en este lugar que sea realmente imposible?",
    "&iquest;Qu&eacute; caracter&iacute;stica de este sitio te recuerda a tu hogar?",
    "&iquest;C&oacute;mo sabes que el tiempo aqu&iacute; trascurre de manera diferente?",
    "&iquest;Por qu&eacute; este lugar te hace recordar tus m&aacute;s profundos miedos?",
    "&iquest;Qu&eacute; aromas inusuales percibes en el aire?",
]; //let PREGUNTAS_LUGAR = [



function print_preguntas_lugar(element_id) {
    var element = document.getElementById(element_id);
    if (!element) return;
    let cosa_text = random_from_list(PREGUNTAS_LUGAR);
    element.innerHTML = print_fortune_cookie(cosa_text);
} //function print_preguntas_lugar(element_id)


let DESCRIPTORES_CIUDAD_BLADES = [
    "Lleno de holl&iacute;n",
    "Adoquines",
    "Sombr&iacute;o",
    "Negro como la tinta",
    "Olores de cocina",
    "Charcos aceitosos",
    "Luz plateada de la luna",
    "Envuelto en niebla",
    "H&uacute;medo",
    "Fr&iacute;o",
    "Barrido por el viento",
    "Oscuro",
    "Paredes de ladrillo",
    "Ecos",
    "Chimeneas",
    "Luces de gas",
    "Luces el&eacute;ctricas",
    "Carruajes",
    "Torres de reloj",
    "Linternas",
    "Humo de pipa",
    "Canales",
    "G&oacute;ndolas",
    "Resbaladizo por la lluvia",
    "G&aacute;rgolas",
    "Ruinas",
    "Campanarios",
    "Puentes",
    "Pasarelas",
    "Andamios",
    "Callejones",
    "Cisternas",
    "Alcantarillas",
    "M&aacute;quinas chirriantes",
    "Herrer&iacute;a"
];


let DUNGEON_PARAMOS_AVENTURADOS_CREADOR = [
    "Raza olvidada",
    "Semidi&oacute;s/demonio",
    "Natural (cuevas...)",
    "Orden religiosa",
    "secta",
    "Humanoide",
    "Enanos",
    "gnomos",
    "Elfos",
    "Mago",
    "demente",
    "Monarca",
    "caudillo",
]; //let DUNGEON_PARAMOS_AVENTURADOS_CREADOR = [



let DUNGEON_PARAMOS_AVENTURADOS_FUNCION = [
    "Fuente",
    "portal",
    "Mina",
    "Tumba",
    "cripta",
    "Prisi&oacute;n",
    "Cubil",
    "madriguera",
    "guarida",
    "Fortaleza",
    "santuario",
    "Capilla",
    "templo",
    "or&aacute;culo",
    "Archivo",
    "biblioteca",
    "Desconocida",
    "misteriosa"
]; //let DUNGEON_PARAMOS_AVENTURADOS_FUNCION = [



let DUNGEON_PARAMOS_AVENTURADOS_RUINA = [
    "Desastre",
    "arcano",
    "Perdici&oacute;n",
    "maldici&oacute;n",
    "Terremoto",
    "incendio",
    "inundaci&oacute;n",
    "Plaga",
    "hambruna",
    "sequ&iacute;a",
    "Infestaci&oacute;n",
    "monstruos",
    "Guerra",
    "invasi&oacute;n",
    "Recursos agotados",
    "Mejores opciones en otro lugar",
    "Ojos desviados",
    "Envidia amarga",
    "Mercado negro",
    "Silencio de clanes",
    "Odio de clase",
    "Corrosivo",
    "Vicio",
    "Corrupci&oacute;n",
    "Golpe de estado",
    "Plaga",
    "Crimen",
    "Estructuras desmoronadas",
    "Desesperaci&oacute;n",
    "Entra&ntilde;as oscuras",
    "Industria en descomposici&oacute;n",
    "Demagogos",
    "Depravados",
    "Clero",
    "Desastre",
    "Epidemia",
    "Drogas",
    "Pobreza",
    "Industria explotadora",
    "&Eacute;lites enemistadas",
    "Carne prohibida",
    "Reubicaciones forzadas",
    "Influencia de pandillas",
    "Tradici&oacute;n odiosa",
    "Muerte inminente",
    "Migrante",
    "Tensiones",
    "Viejos rencores",
    "Traici&oacute;n",
    "Control plutocr&aacute;tico",
    "Suelo envenenado",
    "Fan&aacute;ticos",
    "Liderazgo de marionetas",
    "Raza Odio",
    "Conflicto religioso",
    "Violencia sin sentido",
    "Comercio de esclavos",
    "Medios de comunicaci&oacute;n sobornados",
    "Burocracia retorcida",
    "&Eacute;lites tir&aacute;nicas",
    "Soborno",
    "Hechiceros acad&eacute;micos",
    "L&iacute;nea de sangre alien&iacute;gena",
    "Programa de cr&iacute;a",
    "Poder enterrado",
    "Sectarios",
    "Culto",
    "Cabeza de turco",
    "Salvador",
    "Puerta oscurecida",
    "Radiaci&oacute;n sobrenatural",
    "Fe sucia",
    "Riqueza horrible",
    "Maestros inhumanos",
    "Guarida de monstruos",
    "Ritual masivo",
    "Centro de Reclutamiento",
    "Entidades Depredadoras",
    "Nexo",
    "Secreto",
    "Pacto Terrible",
    "Cazadores Traidores",
]; //let DUNGEON_PARAMOS_AVENTURADOS_RUINA = [



let DUNGEON_PARAMOS_AVENTURADOS_CAUSAS = [
    "Descomposici&oacute;n/deterioro",
    "Tortura/agon&iacute;a",
    "Locura",
    "Todo est&aacute; perdido",
    "Noble sacrificio",
    "Furia salvaje",
    "Supervivencia",
    "Actividad criminal",
    "Secretos/traici&oacute;n",
    "Enga&ntilde;os y trampas",
    "Invasi&oacute;n/infestaci&oacute;n",
    "Facciones en guerra",
    "Creaci&oacute;n/invenci&oacute;n",
    "Elemento",
    "Conocimiento/aprendizaje",
    "Crecimiento/expansi&oacute;n",
    "Creciente",
    "misterio",
    "Transformaci&oacute;n/cambio",
    "Caos y destrucci&oacute;n",
    "Fuerzas oscuras",
    "Conocimiento prohibido",
    "Veneno/enfermedad",
    "Corrupci&oacute;n/plaga",
    "Desastre inminente",
    "Mal",
    "intrigante",
    "Adivinaci&oacute;n/",
    "escudri&ntilde;amiento",
    "Blasfemia",
    "Investigaci&oacute;n",
    "arcana",
    "Fuerzas ocultas",
    "Una antigua maldici&oacute;n",
    "Mutaci&oacute;n",
    "Los muertos sin reposo",
    "Hambre insaciable",
    "Incre&iacute;ble poder",
    "Horrores innombrables",
    "Guerra sagrada",
]; //let DUNGEON_PARAMOS_AVENTURADOS_CAUSAS = [



let DUNGEON_PARAMOS_AVENTURADOS_DETALLES = [
    "Basura",
    "escombros",
    "Huellas",
    "marcas",
    "Se&ntilde;ales de batalla",
    "Escritos",
    "tallas",
    "Advertencia",
    "Criatura muerta",
    "Huesos",
    "restos",
    "Libro",
    "pergamino",
    "mapa",
    "Puerta (o pared) rota",
    "Brisa",
    "viento",
    "aroma",
    "Liquen",
    "musgo",
    "hongos",
    "Rareza",
    "Derrumbe",
    "colapso",
    "Pozo",
    "hoyo",
    "abismo",
    "Pilares",
    "columnas",
    "Puerta",
    "verja cerrada",
    "Huecos",
    "nichos",
    "Puente",
    "escaleras",
    "rampa",
    "Fuente",
    "pozo",
    "estanque",
    "Acertijo",
    "Altar",
    "estrado",
    "tribuna",
    "Estatua",
    "&iacute;dolo",
    "Estanque,",
    "estatua",
    "&iacute;dolo",
    "Conexi&oacute;n a otra mazmorra",
    "Baratijas",
    "Herramientas",
    "Armas",
    "armadura",
    "Suministros",
    "mercanc&iacute;as",
    "Monedas",
    "gemas",
    "joyer&iacute;a",
    "Venenos",
    "pociones",
    "Aventurero",
    "prisionero",
    "Objeto m&aacute;gico",
    "Pergamino",
    "libro",
    "Arma o armadura m&aacute;gica",
    "Artefacto",
    "Alarma",
    "Atrapante",
    "paralizante",
    "Foso",
    "Aplastante",
    "Perforante",
    "trinchante",
    "Cortante",
    "apu&ntilde;aladora",
    "Confusi&oacute;n",
    "laberinto",
    "Gas venenoso",
    "Emboscada",
    "Emboscada M&aacute;gica",
    "Esperando emboscar",
    "Luchando discutiendo",
    "Merodeando",
    "patrullando",
    "Buscando alimento",
    "Comiendo descansando",
    "Protegiendo algo",
    "Traslad&aacute;ndose",
    "Buscando",
    "hurgando",
    "De vuelta a su madriguera",
    "Planeando algo",
    "Durmiendo",
    "Agonizando",
    "Intruso",
    "extra&ntilde;o",
    "Se&ntilde;or de la Plaga",
    "Amo del crimen",
    "Se&ntilde;or de la Guerra",
    "Sumo Sacerdote",
    "Or&aacute;culo",
    "Mago",
    "bruja",
    "alquimista",
    "Monstruo",
    "Esp&iacute;ritu",
    "malvado",
    "fantasma",
    "Se&ntilde;or no muerto",
    "Demonio",
    "Dios Oscuro",
]; //let DUNGEON_PARAMOS_AVENTURADOS_DETALLES = [
