

let LIMINAL_HECHIZOS_EFECTOS = ["EFECTOS_FISICOS", "EFECTOS_ETEREOS"];


let LIMINAL_HECHIZOS_OBJETIVOS = ["ELEMENTOS_FISICOS", "FORMAS_FISICAS", "ELEMENTOS_ETEREOS", "FORMAS_ETEREAS"];


let LIMINAL_HECHIZOS = {
    "EFECTOS_FISICOS": [
        "Animar",
        "Aplastar",
        "Fusionar",
        "Atraer",
        "Disminuir",
        "Coger",
        "Atar",
        "Atar",
        "Dividir",
        "Acelerar",
        "Florecer",
        "Duplicar",
        "Obstaculizar",
        "Consumir",
        "Envolver",
        "Iluminar",
        "Arrastrar",
        "Expandir",
        "Aprisionar",
        "Levitar",
        "Reflejar",
        "Sellar",
        "Abrir",
        "Regenerar",
        "Cambiar de forma",
        "Petrificar",
        "Desgarrar",
        "Blindar",
        "Ajustar Fase",
        "Repeler",
        "Desovar",
        "Perforar",
        "Resucitar",
        "Transmutar",
        "Perseguir",
        "Gritar",
        "Transportar",
    ], //"EFECTOS_FISICOS": [
    "ELEMENTOS_FISICOS": [
        "&Aacute;cido",
        "Cuervo",
        "Vidrio",
        "&Aacute;mbar",
        "Cristal",
        "Miel",
        "Corteza",
        "Ascua",
        "Hielo",
        "Sangre",
        "Colmillo",
        "Insecto",
        "Hueso",
        "Carne",
        "Lava",
        "Arcilla",
        "Hongo",
        "Musgo",
        "Obsidiana",
        "Arena",
        "Alquitr&aacute;n",
        "Aceite",
        "Savia",
        "Espina",
        "Veneno",
        "Serpiente",
        "Vid",
        "Rata",
        "Tend&oacute;n",
        "Agua",
        "Roca",
        "Limo",
        "Madera",
        "Sal",
        "Piedra",
        "Gusano",
    ], //"ELEMENTOS_FISICOS": [
    "FORMAS_FISICAS": [
        "Altar",
        "Carro",
        "Ojo",
        "Armadura",
        "Garra",
        "Fuente",
        "Flecha",
        "Capa",
        "Puerta",
        "Bestia",
        "Coloso",
        "Golem",
        "Cuchilla",
        "Corona",
        "Martillo",
        "Cadena",
        "Elemental",
        "Gancho",
        "Cuerno",
        "Centinela",
        "Tent&aacute;culo",
        "Llave",
        "Sirviente",
        "Trono",
        "M&aacute;scara",
        "Escudo",
        "Antorcha",
        "Monolito",
        "Lanza",
        "Trampa",
        "Pozo",
        "Corcel",
        "Muro",
        "Prisi&oacute;n",
        "Enjambre",
        "Telara&ntilde;a",
    ], //"FORMAS_FISICAS": [
    "EFECTOS_ETEREOS": [
        "Vengar",
        "Convencer",
        "Disipar",
        "Desterrar",
        "Ocultar",
        "Envalentonar",
        "Desconcertar",
        "Ensordecer",
        "Codificar",
        "Cegar",
        "Enga&ntilde;ar",
        "Energizar",
        "Encantar",
        "Descifrar",
        "Esclarecer",
        "Comunicar",
        "Disfrazar",
        "Enfurecer",
        "Insoportar",
        "Anular",
        "Calmar",
        "Prever",
        "Paralizar",
        "Convocar",
        "Embriagar",
        "Revelar",
        "Aterrar",
        "Enloquecer",
        "Repugnar",
        "Proteger",
        "Hipnotizar",
        "Escudri&ntilde;ar",
        "Cansar",
        "Leer",
        "Leer la mente",
        "Silenciar",
        "Marchitar",
    ], //"EFECTOS_ETEREOS": [
    "ELEMENTOS_ETEREOS": [
        "Ceniza",
        "Ectoplasma",
        "Luz",
        "Caos",
        "Fuego",
        "Rel&aacute;mpago",
        "Distorsi&oacute;n",
        "Niebla",
        "Memoria",
        "Sue&ntilde;o",
        "Fantasma",
        "Mente",
        "Polvo",
        "Armon&iacute;a",
        "Mut&aacute;geno",
        "Eco",
        "Coraz&oacute;n",
        "Negaci&oacute;n",
        "Plaga",
        "Humo",
        "Trueno",
        "Plasma",
        "Nieve",
        "Tiempo",
        "Probabilidad",
        "Alma",
        "Vac&iacute;o",
        "Lluvia",
        "Estrella",
        "Warp",
        "Putrefacci&oacute;n",
        "&Eacute;xtasis",
        "Susurro",
        "Sombra",
        "Vapor",
        "Viento",
    ], //"ELEMENTOS_ETEREOS": [
    "FORMAS_ETEREAS": [
        "Aura",
        "Burbuja",
        "Cono",
        "Baliza",
        "Llamada",
        "Cubo",
        "Haz",
        "Cascada",
        "Danza",
        "Explosi&oacute;n",
        "C&iacute;rculo",
        "Disco",
        "Gota",
        "Nube",
        "Campo",
        "Bisagra",
        "Espiral",
        "Forma",
        "Mirada",
        "Pir&aacute;mide",
        "Enjambre",
        "Bucle",
        "Rayo",
        "Torrente",
        "Momento",
        "Fragmento",
        "Toque",
        "Nexo",
        "Esfera",
        "V&oacute;rtice",
        "Portal",
        "Aerosol",
        "Onda",
        "Pulso",
        "Tormenta",
        "Palabra",
    ], //"FORMAS_ETEREAS": [
}; //LIMINAL_HECHIZOS = [



let SCRAPS_INGREDIENTES = [
    "Hielo",
    "&Aacute;mbar",
    "Resina",
    "Arco&iacute;ris",
    "Drag&oacute;n",
    "Amable",
    "Sombra",
    "Zumbador",
    "Bailador",
    "&Aacute;ngel",
    "Seda",
    "Furiosa",
    "Ceniza",
    "Hueco",
    "Sol",
    "Luna",
    "Viento",
    "Radiante",
    "Escarlata",
    "Coral",
    "Gaseoso",
    "Dorado",
    "Flotante",
    "Fantasma",
    "Lluvia",
    "Pimienta",
    "&Oacute;xido",
    "Tembloroso",
    "Tormenta",
    "Haciendo cabriolas",
    "Carmes&iacute;",
    "Oc&eacute;ano",
    "Estrella",
    "Resplandeciente",
    "Sue&ntilde;o",
    "Nube",
    "Plata",
    "Ceniza",
]; // let SCRAPS_INGREDIENTES = [


let SCRAPS_MATERIALES = [
    "Luminoso",
    "Animado",
    "de piel",
    "de Pelo",
    "Escamoso",
    "Lagrimoso",
    "Astado",
    "Cornamenta",
    "&Oacute;seo",
    "Con Garras",
    "Lechoso",
    "de C&aacute;scara de huevo",
    "Rodante",
    "Con Setas",
    "Vegetal",
    "Floral",
    "Con P&eacute;talos",
    "Jarabe",
    "Jugo",
    "Savia",
    "En Hojas",
    "Espinoso",
    "De Madera",
    "Laminado",
    "De Corcho",
    "Semilla",
    "Espora",
    "Ra&iacute;z",
    "Mineral",
    "Petreo",
    "Joya",
    "Met&aacute;lico",
    "F&eacute;rreo",
    "Salino",
    "Arenoso",
    "Polvoriento",
    "Cristalino",
    "Aceitoso",
    "Vaporoso",
]; //let SCRAPS_MATERIALES = [



let SCRAPS_DIFICULTADES = [
    "Escondido",
    "Aislado",
    "En Alto",
    "Fr&aacute;gil",
    "Tenue",
    "En Profundidad",
    "Enganchado a algo",
    "Evasivo",
    "Asustadizo",
]; //let SCRAPS_DIFICULTADES = [



let OBJETO_FORMA = [
    "Poci&oacute;n",
    "Anillo",
    "Vara",
    "Pergamino",
    "Proyectil",
    "Esfera",
    "Escarabeo",
    "Prenda",
    "Zapatos",
    "Escoba",
    "Campanilla",
    "Cubo",
    "Gafas",
    "Casco",
    "Collar",
    "Piedra",
    "Polvo",
    "Aceite",
    "Incensario",
    "Corona",
    "&Aacute;ngulos",
    "Canon",
    "cr&iacute;ptico",
    "Canto",
    "esot&eacute;rico",
    "Encantamiento",
    "mayor",
    "Conjuraci&oacute;n",
    "oculta",
    "Maleficio",
    "iluminado",
    "Inscripci&oacute;n",
    "inefable",
    "Invocaci&oacute;n",
    "inexorable",
    "R&uacute;brica",
    "invencible",
    "Canci&oacute;n",
    "menor",
    "Texto",
    "poderoso",
    "Palabras",
    "rapaces",
    "Secreto",
]; //let OBJETO_FORMA = [



let OBJETO_USO = [
    "Dispararlo",
    "Arrojarlo",
    "Abrirlo",
    "Romperlo",
    "Ingerirlo",
    "Aplic&aacute;rselo",
    "Pronunciar algo en voz alta",
    "Observarlo",
    "Pon&eacute;rselo",
    "Agitarlo",
    "Cerrarlo",
    "Atarlo",
    "Encajarlo correctamente",
    "Conectar dos piezas o partes",
    "Tocar una superficie",
    "Aspirarlo",
    "Golpearlo",
    "Trazar un s&iacute;mbolo con &eacute;l",
    "Hacer que emita sonido",
    "Pulsar un bot&oacute;n",
    "Alfombra",
]; //let OBJETO_USO = [",


let OBJETO_DURACION = [
    "Concentraci&oacute;n",
    "unos segundos",
    "pocos minutos",
    "pocas horas",
    "Un d&iacute;a",
]; //let OBJETO_DURACION = [


let OBJETO_EFECTO = [
    "Clariaudiencia",
    "Clarividencia",
    "Sentir tesoro",
    "Rayos X",
    "Detectar enemigos",
    "Detectar magia",
    "Detectar secretos y trampas",
    "Sentir intenciones",
    "Leer pensamiento",
    "Comprender lenguas",
    "Fuerza aumentada",
    "Resistencia al cansancio",
    "Respirar agua",
    "Habilidad de combate mejorada",
    "Seducci&oacute;n irresistible",
    "Apariencia imponente",
    "Protecci&oacute;n contra un elemento",
    "Resistencia al hambre y la sed",
    "Agarre inescapable",
    "Trabajar por diez",
    "Debilitar",
    "Causar muerte",
    "Putrefacci&oacute;n",
    "Causar da&ntilde;o leve",
    "Causar da&ntilde;o grave",
    "Aniquilaci&oacute;n de un enemigo concreto",
    "Absorber energ&iacute;a vital",
    "Envenenar",
    "Enfermedad",
    "Agostar cultivos",
    "Transformaci&oacute;n animal",
    "Transformaci&oacute;n en piedra",
    "Encoger",
    "Aumentar",
    "Transformaci&oacute;n en gas",
    "Quimerismo",
    "Invocar el fuego",
    "Invocar el hielo",
    "Invocar el rayo",
    "Invocar el viento",
    "Invocar el agua",
    "Predecir el tiempo",
    "Invocar el viento",
    "Respirar agua",
    "Niebla s&oacute;lida",
    "Hablar con el viento",
    "Insonoridad",
    "Invisibilidad",
    "Camuflaje",
    "Apariencia inocua",
    "Invocar escondite",
    "Crear distracci&oacute;n",
    "Caminar por el techo",
    "Velo de sombras",
    "Luz secreta",
    "Volar",
    "Caminar sobre el agua",
    "Encontrar el camino",
    "Trepar como ara&ntilde;a",
    "Fricci&oacute;n cero",
    "Propulsi&oacute;n",
    "Abrir portal",
    "Hablar con los muertos",
    "Adivinaci&oacute;n",
    "Hacer reposar un fantasma",
    "Maldecir",
    "Controlar no muertos",
    "Llamar esp&iacute;ritu elemental",
    "Crear ilusi&oacute;n",
    "Paralizar",
    "Inducir miedo",
    "Fr&iacute;o sobrecogedor",
    "Curaci&oacute;n leve",
    "Curaci&oacute;n mayor",
    "Recuperar miembros",
    "Regeneraci&oacute;n",
    "Retirar enfermedades",
    "Retirar hambre y sed",
    "Invocar comida y agua",
    "Refugio m&aacute;gico",
    "Devolver sentidos",
    "Resurrecci&oacute;n",
    "Cancelar magia",
    "Guarda contra un tipo de criatura",
    "Guarda contra magia de muerte",
    "Guarda contra magia de elementos",
    "Guarda contra magia de espectros",
    "Devolver magia",
    "Guarda contra enemigos",
    "Retirar maldiciones",
    "Revertir transformaci&oacute;n",
    "Invocar devorador de magia",
    "Cegar",
    "Velocidad",
    "Teletransporte",
    "Flotar",
    "Volar",
    "Caminar sobre el agua",
    "Encontrar el camino",
    "Trepar como ara&ntilde;a",
    "Fricci&oacute;n cero",
    "Propulsi&oacute;n",
    "Abrir portal",
    "Hablar con los muertos",
    "Adivincaci&oacute;n",
    "Hacer reposar un fantasma",
    "Maldecir",
    "Controlar no muertos",
    "Llamar esp&iacute;ritu elemental",
    "Crear ilusi&oacute;n",
    "Paralizar",
    "Inducir miedo",
    "Fr&iacute;o sobrecogedor",
    "Curaci&oacute;n leve",
    "Curaci&oacute;n mayor",
    "Recuperar miembros",
    "Regeneraci&oacute;n",
    "Retirar enfermedades",
    "Retirar hambre y sed",
    "Invocar comida y agua",
    "Refugio m&aacute;gico",
    "Devolver sentidos",
    "Resurrecci&oacute;n",
    "Cancelar magia",
    "Guarda contra un tipo de criatura",
    "Guarda contra magia de muerte",
    "Guarda contra magia de elementos",
    "Guarda contra magia de espectros",
    "Devolver magia",
    "Guarda contra enemigos",
    "Retirar maldiciones",
    "Revertir transformaci&oacute;n",
    "Invocar devorador de magia",
    "Convertirse en un animal",
    "Convertirse en un objeto",
    "Transformaci&oacute;n en l&iacute;quido",
    "Sentidos agudizados",
    "Invocar el fuego",
    "Invocar el hielo",
    "Invocar el rayo",
    "Invocar el viento",
    "Invocar el agua",
    "Predecir el tiempo",
    "Invocar el viento",
    "Respirar agua",
    "Niebla s&oacute;lida",
    "Hablar con el viento",
    "Insonoridad",
    "Invisibilidad",
    "Camuflaje",
    "Apariencia inocua",
    "Invocar escondite",
    "Crear distracci&oacute;n",
    "Caminar por el techo",
    "Velo de sombras",
    "Luz secreta",
    "Cegar",
    "Velocidad",
    "Teletransporte",
    "Flotar",
    "Volar",
    "Caminar sobre el agua",
    "Encontrar el camino",
    "Trepar como ara&ntilde;a",
    "Fricci&oacute;n cero",
    "Propulsi&oacute;n",
    "Abrir portal",
    "Hablar con los muertos",
    "Adivincaci&oacute;n",
    "Hacer reposar un fantasma",
    "Maldecir",
    "Controlar no muertos",
    "Llamar esp&iacute;ritu elemental",
    "Crear ilusi&oacute;n",
    "Paralizar",
    "Inducir miedo",
    "Fr&iacute;o sobrecogedor",
    "Curaci&oacute;n leve",
    "Curaci&oacute;n mayor",
    "Recuperar miembros",
    "Regeneraci&oacute;n",
    "Retirar enfermedades",
    "Retirar hambre y sed",
    "Invocar comida y agua",
    "Refugio m&aacute;gico",
    "Devolver sentidos",
    "Resurrecci&oacute;n",
    "Cancelar magia",
    "Guarda contra un tipo de criatura",
    "Guarda contra magia de muerte",
    "Guarda contra magia de elementos",
    "Guarda contra magia de espectros",
    "Devolver magia",
    "Guarda contra enemigos",
    "Retirar maldiciones",
    "Revertir transformaci&oacute;n",
    "Invocar devorador de magia",
    "Vuela",
    "Telekinesis",
    "Pirokinesis",
    "Pecognici&oacute;n",
    "Telepat&iacute;a",
    "Protecci&oacute;n",
]; //let OBJETO_EFECTO = [



let OBJETO_MITICO = [
    "Placa de miembro del Alto Colegio de Magos de Tamniir",
    "Grito de trol embotellado",
    "Estandarte de los mil soles",
    "Puertas del Gran Templo de Rhahissha",
    "Servidor de fuego",
    "Zuecos de peral sabio",
    "El Libro de Muchos",
    "Equipo vacacional de Grazzus el Indolente",
    "Crema antiacn&eacute; con sangre de sirena",
    "Escriban&iacute;a autom&aacute;tica",
]; //let OBJETO_MITICO = [



let OTRO_HECHIZO = [
    "<u>Adherirse:</u> un objeto est&aacute; cubierto de una baba extremadamente pegajosa.",
    "<u>Ancla:</u> un cable fuerte brota de sus brazos y se adhiere a dos puntos dentro de los 15 metros a cada lado.",
    "<u>Objeto animado:</u> un objeto obedece tus &oacute;rdenes lo mejor que puede.",
    "<u>Antropomorfizar:</u> un animal adquiere inteligencia humana o apariencia humana por un d&iacute;a.",
    "<u>Ojo arcano:</u> puedes ver a trav&eacute;s de un globo ocular flotante m&aacute;gico que vuela a tu disposici&oacute;n.",
    "<u>Prisi&oacute;n Astral:</u> Un objeto est&aacute; congelado en el tiempo y espacio dentro de una esfera de cristal invulnerable.",
    "<u>Atraer:</u> dos objetos se atraen fuertemente magn&eacute;ticamente si se acercan a 3 metros.",
    "<u>Ilusi&oacute;n auditiva:</u> Creas sonidos ilusorios que parecen provenir de una direcci&oacute;n de tu elecci&oacute;n.",
    "<u>Balbucear:</u> Una criatura debe repetir en voz alta y clara todo lo que piensa. Por lo dem&aacute;s, es mudo.",
    "<u>Flor Cebo:</u> Una planta brota del suelo que emana el olor de la carne en descomposici&oacute;n.",
    "<u>Forma de bestia:</u> t&uacute; y tus posesiones se transforman en un animal mundano.",
    "<u>Confundir:</u> una criatura de tu elecci&oacute;n no puede formar nuevos recuerdos a corto plazo mientras dure el hechizo.",
    "<u>Cambio de cuerpo:</u> cambias de cuerpo con una criatura que tocas. Si un cuerpo muere, el otro tambi&eacute;n muere.",
    "<u>Encanto:</u> una criatura que puedes ver te trata como a un amigo.",
    "<u>Comprende:</u> dominas todos los idiomas por un corto tiempo.",
    "<u>Comando:</u> un objetivo obedece un solo comando de tres palabras que no le causa da&ntilde;o.",
    "<u>Cono de espuma:</u> Espuma densa sale de tu mano y cubre el objetivo.",
    "<u>Plantas de control:</u> las plantas y los &aacute;rboles cercanos te obedecen y adquieren la capacidad de moverse a un ritmo lento.",
    "<u>Controlar el clima:</u> puede alterar el tipo de clima a voluntad, pero no puede controlarlo de otra manera.",
    "<u>Cure Wounds:</u> Restaura 1/4 de su vida m&aacute;xima por d&iacute;a a una criatura que puedas tocar.",
    "<u>Sordo:</u> Todas las criaturas cercanas quedan sordas.",
    "<u>Detectar magia:</u> puedes ver o escuchar auras m&aacute;gicas cercanas.",
    "<u>Desmontar:</u> cualquiera de las partes de su cuerpo se puede separar y volver a colocar a voluntad, sin causar dolor ni da&ntilde;o, bajo tu control.",
    "<u>Disfraz:</u> puedes alterar la apariencia de un personaje a voluntad siempre que siga siendo humanoide.",
    "<u>Desplazar:</u> un objeto parece estar hasta 5 metros de su posici&oacute;n real.",
    "<u>Terremoto:</u> El suelo comienza a temblar violentamente. Las estructuras pueden da&ntilde;arse o colapsar.",
    "<u>Elasticidad:</u> Tu cuerpo puede estirarse hasta 3 metros.",
    "<u>Muro elemental:</u> un muro recto de hielo o fuego de 15 metros de largo y 3 metros de alto se eleva desde el suelo.",
    "<u>Filch:</u> un elemento visible se teletransporta a tus manos.",
    "<u>Bengala:</u> una brillante bola de energ&iacute;a dispara un rastro de luz hacia el cielo, revelando tu ubicaci&oacute;n a amigos o enemigos.",
    "<u>Nube de niebla:</u> una densa niebla se extiende desde ti.",
    "<u>Frenes&iacute;:</u> una criatura cercana estalla en un frenes&iacute; de violencia.",
    "<u>Puerta:</u> Se abre un portal a un plano aleatorio.",
    "<u>Cambio de gravedad:</u> puedes cambiar la direcci&oacute;n de la gravedad, pero solo para ti.",
    "<u>Codicia:</u> una criatura desarrolla la abrumadora necesidad de poseer un objeto visible de tu elecci&oacute;n.",
    "<u>Prisa:</u> Tu velocidad de movimiento se triplica.",
    "<u>Odio:</u> Una criatura desarrolla un profundo odio hacia otra criatura o grupo y desea destruirlos.",
    "<u>Escuche susurros:</u> puede escuchar sonidos d&eacute;biles con claridad.",
    "<u>Flotar:</u> Un objeto flota, sin fricci&oacute;n, 60 cent&iacute;metros sobre el suelo.Puede contener hasta un humanoide.",
    "<u>Hipnotizar:</u> Una criatura entra en trance y responder&aacute; con sinceridad una pregunta de s&iacute; o no que le hagas.",
    "<u>Toque helado:</u> una gruesa capa de hielo se extiende sobre una superficie tocada, hasta 3 metros de radio.",
    "<u>Identificar propietario:</u> Aparecen letras sobre el objeto que toca, deletreando el nombre de los propietarios del objeto, si los hay.",
    "<u>Ilumina:</u> Una luz flotante se mueve a tu orden.",
    "<u>Atadura invisible:</u> dos objetos que se encuentren a menos de 3 metros de distancia entre s&iacute; se pueden mover m&aacute;ximo 3 metros.",
    "<u>Toc:</u> una cerradura mundana o m&aacute;gica cercana se abre, en voz alta.",
    "<u>​​Salto:</u> saltas hasta 3 metros de altura, una vez.",
    "<u>Aire l&iacute;quido:</u> el aire que te rodea se vuelve apto para nadar.",
    "<u>Magic Dampener:</u> todos los efectos m&aacute;gicos cercanos tienen su efectividad reducida a la mitad.",
    "<u>Manse:</u> aparece una caba&ntilde;a robusta y amueblada durante 12 horas. Puede permitir y prohibir la entrada a &eacute;l a voluntad.",
    "<u>Marble Craze:</u> tus bolsillos est&aacute;n llenos de canicas y se volver&aacute;n a llenar cada 30 segundos.",
    "<u>Mascarada:</u> la apariencia y la voz de un personaje se vuelven id&eacute;nticas a las de un personaje que tocas.",
    "<u>Sentido:</u> Elige un tipo de objeto (llave, oro, flecha, jarra, etc.). Puedes sentir ese objeto m&aacute;s cercano.",
    "<u>Escudo:</u> una criatura que tocas est&aacute; protegida de los ataques mundanos durante un minuto.",
    "<u>Shroud:</u> una criatura que tocas es invisible hasta que se mueve.",
    "<u>Shuffle:</u> dos criaturas que puedes ver cambian de lugar instant&aacute;neamente.",
    "<u>Sue&ntilde;o:</u> una criatura que puedes ver cae en un sue&ntilde;o ligero.",
    "<u>Resbaladizo:</u> Cada superficie en un radio de 10 metros se vuelve extremadamente resbaladiza.",
    "<u>Forma de humo:</u> Tu cuerpo se convierte en un humo vivo que puedes controlar.",
    "<u>Sniff:</u> puedes oler incluso los m&aacute;s leves rastros de olores.",
    "<u>Tabaco:</u> La fuente de cualquier luz mundana que puedas ver se apaga instant&aacute;neamente.",
    "<u>Ordenar:</u> los elementos inanimados se ordenan seg&uacute;n las categor&iacute;as que establezcas.",
    "<u>Espect&aacute;culo:</u> Aparece una ilusi&oacute;n claramente falsa pero impresionante de tu elecci&oacute;n, bajo tu control.",
    "<u>Sierra m&aacute;gica:</u> una cuchilla giratoria sale volando de tu pecho y elimina cualquier material vegetal en su camino.",
    "<u>Spider Climb:</u> puedes trepar superficies como una ara&ntilde;a.",
    "<u>Invocar cubo:</u> una vez por segundo puedes invocar o desterrar un cubo de tierra de 1 metro de ancho.",
    "<u>Enjambre:</u> Te conviertes en un enjambre de cuervos, ratas o pira&ntilde;as. Solo puedes ser da&ntilde;ado por ataques explosivos.",
    "<u>Telequinesis:</u> puedes mover mentalmente 1 art&iacute;culo de menos de 60 libras.",
    "<u>Telepat&iacute;a:</u> dos criaturas pueden escuchar los pensamientos de la otra, sin importar la distancia entre ellas.",
    "<u>Teletransporte:</u> un objeto o persona que puede ver se transporta de un lugar a otro en un radio de 15 metros.",
    "<u>Se&ntilde;uelo objetivo:</u> un objeto que tocas se convierte en el objetivo de cualquier hechizo cercano.",
    "<u>Matorral:</u> Un matorral de &aacute;rboles y maleza densa de hasta 15 metros de ancho brota repentinamente.",
    "<u>Invocar &iacute;dolo:</u> una estatua de piedra tallada del tama&ntilde;o de una mula se eleva desde el suelo.",
    "<u>Control de tiempo:</u> el tiempo en una burbuja de 15 metros se ralentiza o aumenta en un 10 % durante 30 segundos.",
    "<u>Visi&oacute;n Verdadera:</u> Ves a trav&eacute;s de todas las ilusiones cercanas.",
    "<u>Manantial:</u> Aparece un manantial de agua de mar.",
    "<u>Visi&oacute;n:</u> Controlas completamente lo que ve una criatura.",
    "<u>Ilusi&oacute;n visual:</u> aparece una ilusi&oacute;n silenciosa, inm&oacute;vil y del tama&ntilde;o de una habitaci&oacute;n que elijas.",
    "<u>C&iacute;rculo:</u> aparece en el suelo un c&iacute;rculo plateado de 15 metros de ancho. Elige una especie que no pueda cruzarla.",
    "<u>Telara&ntilde;a:</u> Tus mu&ntilde;ecas disparan gruesas correas.",
    "<u>Widget:</u> una versi&oacute;n primitiva de una herramienta o elemento dibujado aparece ante ti y desaparece despu&eacute;s de unos instantes.",
    "<u>Marca del Mago:</u> tu dedo puede disparar un chorro de pintura del color que quieras. Solo es visible para ti a cualquier distancia y a trav&eacute;s de cualquier objeto.",
    "<u>Visi&oacute;n de rayos X:</u> puede ver a trav&eacute;s de paredes, suciedad, ropa, etc.",
    "Doblar el coraz&oacute;n del rey</u>",
    "<u>Conversar con el v&iacute;nculo</u>",
    "<u>La espada carmes&iacute;</u>",
    "<u>Ojos de la mente distante</u>",
    "<u>Banda de ancestros libres</u>",
    "<u>Escapar</u>",
    "<u>El c&iacute;rculo de los ojos internos</u>",
    "<u>Polvo de fregar</u>",
    "<u>Falso v&iacute;nculo</u>",
    "<u>Cerrar el camino</u>",
    "<u>Conjuro del tres veces</u>",
    "<u>La casita sin apariencia</u>",
    "<u>Ojo compartido</u>",
    "<u>Ventanas distantes</u>",
    "<u>Sello de Alarma</u>",
    "<u>Amistad de los Unos</u>",
    "<u>La L&aacute;mpara Negra</u>",
    "<u>Matar la Debilidad</u>",
    "<u>La Expurgaci&oacute;n Roja</u>",
    "<u>El Misericordioso</u>",
    "<u>Estante de Ibn</u>",
    "<u>Luz Purificadora</u>",
    "<u>Las Nieblas</u>",
    "<u>Los Gusanos Voraces</u>",
    "<u>Espada Baraka</u>",
    "<u>Amanecer</u>",
    "<u>Sabiendo</u>",
    "<u>Incensar a los torcidos</u>",
    "<u>Los mensajeros del aire</u>",
    "<u>El sello de los amarillentos</u>",
    "<u>El sello de la flagelaci&oacute;n</u>",
    "<u>Rito del cuchillo mojado</u>",
    "<u>Road Fang Solomon</u>",
    "<u>La quintaesencia</u>",
    "<u>El sello de los ahogados</u>",
    "<u>El signo del rey</u>",
    "<u>La marca bermell&oacute;n</u>",
    "<u>Reyes de carne</u>",
    "<u>Sello de santidad del umbral de los justos</u>",
    "<u>Verdades escritas en rojo</u>",
    "<u>El bast&oacute;n de volver atr&aacute;s</u>",
    "<u>La hoja plateada del sacrificio</u>",
    "<u>Abriendo el sello</u>",
    "<u>Caminante bajo la tierra</u>",
    "<u>El caminante bajo la luna</u>",
    "<u>Susurros del escriba</u>",
]; //let OTRO_HECHIZO = [



function print_magia(element_id) {
    var element = document.getElementById(element_id);
    if (!element) return;

    var html_code = "";

    let efecto_hechizo = random_from_list(LIMINAL_HECHIZOS_EFECTOS);
    let objetivo_hechizo = random_from_list(LIMINAL_HECHIZOS_OBJETIVOS);
    let hechizo = '<u>Hechizo:</u><br/>';
    hechizo += random_from_list(LIMINAL_HECHIZOS[efecto_hechizo]);
    hechizo += '<br/>';
    hechizo += random_from_list(LIMINAL_HECHIZOS[objetivo_hechizo]);
    html_code += print_fortune_cookie(hechizo);

    //Ingredientes:
    let ingrediente = '';

    for (let i=0; i<2; i++) {
        ingrediente = '<u>Ingrediente:</u><br/>';
        ingrediente += random_from_list(SCRAPS_INGREDIENTES);
        ingrediente += ' ';
        ingrediente += random_from_list(SCRAPS_INGREDIENTES);
        ingrediente += '<br/>';
        ingrediente += random_from_list(SCRAPS_MATERIALES);
        ingrediente += '<br/>';
        ingrediente += '(' + random_from_list(SCRAPS_DIFICULTADES) + ')';
        html_code += '<br/>';
        html_code += print_fortune_cookie(ingrediente);
    }; //for (let i=0; i<2; i++) {

    let objeto_html = '<u>Objeto de un uso:</u><br/>';
    objeto_html += 'Forma: ' + random_from_list(OBJETO_FORMA);
    objeto_html += '<br/>';
    objeto_html += 'Uso: ' + random_from_list(OBJETO_USO);
    objeto_html += '<br/>';
    objeto_html += 'Duraci&oacute;n: ' + random_from_list(OBJETO_DURACION);
    objeto_html += '<br/>';
    objeto_html += 'Efecto: ' + random_from_list(OBJETO_EFECTO);

    html_code += '<br/>';
    html_code += print_fortune_cookie(objeto_html);


    let objeto_mitico = '<u>Objeto m&iacute;tico:</u><br/>';
    objeto_mitico += random_from_list(OBJETO_MITICO);
    html_code += '<br/>';
    html_code += print_fortune_cookie(objeto_mitico);


    let otro_hechizo = random_from_list(OTRO_HECHIZO);
    html_code += '<br/>';
    html_code += print_fortune_cookie(otro_hechizo);

    element.innerHTML = html_code;
    element.scrollTop = "0";
}; //function print_magia(element_id)
