var MECANISMOS = [
    "Contactos criminales",
    "Visiones",
    "M&uacute;sculo",
    "Una mente maravillosa",
    "Habilidad con un arma concreta",
    "Una voz clara",
    "Hechicer&iacute;a encubierta",
    "Una apariencia impactante",
    "Vastos conocimientos del lugar",
    "Una melod&iacute;a pegadiza",
    "Sangre noble",
    "Inventiva",
    "Un objeto &uacute;nico en su especie",
    "Hornear",
    "Destino especial",
    "Destilar",
    "Perspectiva &uacute;nica",
    "Fundir metales",
    "Conocimiento oculto",
    "Tallar madera",
    "Consciencia m&aacute;gica",
    "Escribir",
    "Ascendencia anormal",
    "Inmunidad al fuego",
    "Ventaja pol&iacute;tica",
    "Cocinar",
    "Ligado a un monstruo",
    "Contar historias",
    "Un secreto",
    "Eliminar plagas",
    "Amor verdadero",
    "Mentir",
    "Un coraz&oacute;n inocente",
    "Lo menos extraordinario",
    "Un plan para el crimen perfecto",
    "Sensualidad irresistible",
    "Un billete de ida al para&iacute;so",
    "Aplomo indefinible",
    "Una veta misteriosa",
    "Talento con los enredos",
    "Dinero, dinero y dinero",
    "Ruedas de acero pulido",
    "Bendici&oacute;n divina",
    "Una alfombra m&aacute;gica",
    "Inmunidad legal",
    "Un sinf&iacute;n de ideas",
    "Profec&iacute;a",
    "Persistencia",
    "T&eacute;cnicas secretas de artes marciales",
    "Un mont&oacute;n de comida",
    "Un anillo de poder",
    "Un camino oculto",
    "Un muy necesario saco de patatas",
    "Piedad",
    "Un coraz&oacute;n",
    "Resistencia a la enfermedad",
    "Una posici&oacute;n fortificada",
    "Una biblioteca",
    "Crear leyes",
    "Don de gentes",
    "Idiomas",
    "L&iacute;nea de sangre",
    "Un ojo avispado",
    "Un conjuro innato",
    "Resistencia",
    "Equilibrio",
    "Un lugar seguro",
    "Almas",
    "Velocidad",
    "Misteriosos benefactores",
    "Sentido del bien y el mal",
    "Nervios de acero",
    "Certeza",
    "Enga&ntilde;ar",
    "Atenci&oacute;n al detalle",
    "Un lobo entrenado",
    "Sacrificio heroico",
    "Una hermana perdida y reencontrada",
    "Sentido de la direcci&oacute;n",
    "Una flecha con tu nombre en ella",
    "Una gran idea",
    "Un nombre verdadero",
    "Una entrada secreta a la ciudad",
    "Suerte",
    "El amor de alguien poderoso",
    "La atenci&oacute;n de entes sobrenaturales",
    "Lealtad incuestionable",
    "Amabilidad",
    "Fruta ex&oacute;tica",
    "Extra&ntilde;os tatuajes",
    "Veneno",
    "Una barba majestuosa",
    "Memoria perfecta",
    "Un libro en un extra&ntilde;o idioma",
    "La lengua de los p&aacute;jaros",
    "Poder sobrecogedor",
    "La llave de una puerta importante",
    "Delirios de grandeza",
    "Forja de metales",
    "El viento a su favor y poco peso a sus espaldas"
]; //var MECANISMOS = [
