let CLASE_MONSTRUO = [
    "ALIEN&Iacute;GENA",
    "ANIMADO",
    "ELEMENTAL",
    "HUMANOIDE",
    "INSECTO",
    "ANIMAL",
    "BESTIA",
    "AMORFO",
    "PLANTA",
    "NO MUERTO",
]; //let CLASE_MONSTRUO


let ATRIBUTOS_MONSTRUOS = [
    "Forma de pez/batracio",
    "Apestoso",
    "Boca gigante",
    "M&uacute;ltiples Bocas",
    "Tent&aacute;culos",
    "Muchas extremidades",
    "Vestido extra&ntilde;o",
    "De pesadilla",
    "Ojos m&uacute;ltiples",
    "Goteo",
    "Hielo",
    "Congelado",
    "Levitar/Volar",
    "Como insecto",
    "Como un gusano",
    "Aspecto humanoide",
    "&Oacute;seo",
    "Colores extra&ntilde;os",
    "Como una serpiente",
    "Acu&aacute;tico",
    "Humanoide",
    "De madera",
    "De piedra",
    "Inscrito con s&iacute;mbolos",
    "Exuda vapor o humo",
    "De cosas comunes",
    "Aspecto animal",
    "De sustancia inusual",
    "Empu&ntilde;a un arma",
    "Ojos brillantes",
    "Ruidoso",
    "De metal",
    "Desmoron&aacute;ndose",
    "Cambia de forma",
    "Levitar/Volar",
    "Rob&oacute;tico",
    "Gaseoso",
    "&Iacute;gneo",
    "Como una nube",
    "De energ&iacute;a/electricidad",
    "Levitar/volar",
    "De tierra",
    "De roca/metal",
    "Sustancia inusual",
    "Humanoide",
    "Forma que fluye",
    "S&oacute;lido",
    "Con garras",
    "De agua",
    "L&iacute;quido",
    "De elementos peque&ntilde;os",
    "Muy feo",
    "Con dientes",
    "Primitivo",
    "Colmillos",
    "Orejas puntiagudas",
    "Bellas caracter&iacute;sticas",
    "Ropa primitiva",
    "Empu&ntilde;ando un arma",
    "Armadura",
    "Cuernos",
    "Color de piel raro",
    "Muy inteligente",
    "Tonto",
    "Reptil",
    "Cola",
    "Hermoso/a",
    "Ar&aacute;cnido",
    "Carapaz&oacute;n/acorazado",
    "Cangrejo/artr&oacute;podo",
    "Peludo",
    "Mand&iacute;bulas",
    "M&uacute;ltiples piernas",
    "Gusano",
    "Humanoide",
    "Pinzas/garras",
    "Trepador pared/techo",
    "Ojos en antenas",
    "M&uacute;ltiples ojos",
    "Acu&aacute;tico",
    "Molusco",
    "&Aacute;gil",
    "Con alas",
    "Colores extra&ntilde;os",
    "Aguij&oacute;n",
    "Peludo",
    "Garras",
    "Dientes afilados",
    "Cola",
    "Pelo largo",
    "Feo",
    "P&aacute;jaro",
    "Color extra&ntilde;o",
    "Gru&ntilde;endo",
    "Saltador",
    "Colmillos",
    "Pezu&ntilde;as",
    "Mam&iacute;fero",
    "Manchado",
    "Reptil",
    "Acu&aacute;tico",
    "Anfibio",
    "Alas",
    "Cuernos/Astas",
    "Dientes afilados",
    "Ojos brillantes",
    "Mezcla de animales",
    "Alas",
    "Cuernos",
    "Forma de p&aacute;jaro",
    "Mam&iacute;fero",
    "Reptil",
    "Acu&aacute;tico",
    "Cola",
    "M&uacute;ltiples ojos",
    "Tent&aacute;culos",
    "Colores extra&ntilde;os",
    "Varias extremidades",
    "Peludo",
    "L&iacute;quido",
    "Amorfo",
    "M&uacute;ltiples ojos/bocas",
    "Pegajoso",
    "Tent&aacute;culos/bocas",
    "Burbujeante",
    "Gaseoso",
    "Transl&uacute;cido",
    "Flotar/Levitar/Volar",
    "Negro como la tinta",
    "Verde P&uacute;rpura",
    "Marr&oacute;n",
    "Gelatinoso",
    "Cambiaformas",
    "Forma concreta",
    "Pulsante/tranparente",
    "Trepador pared/techo",
    "Arb&oacute;reo",
    "Enredaderas/tent&aacute;culos",
    "Hongo",
    "Agujas",
    "Colorido",
    "Acu&aacute;tico",
    "Fauces con dientes",
    "Flores / esporas",
    "Arraigado en el suelo",
    "Puede volar/flotar",
    "Forma humanoide",
    "Conjunto de plantas",
    "Hojas",
    "Apesta/venenoso",
    "Piernas motrices",
    "Ra&iacute;ces que se mueven",
    "Con corteza",
    "Carn&iacute;voro",
    "Decaido/se deshace",
    "Esquel&eacute;tico",
    "Insustancial",
    "Sombra",
    "Fr&iacute;o",
    "Maloliente",
    "Silencioso",
    "Asqueroso",
    "Parece vivo",
    "Retorcido/mezclado",
    "Momificado",
    "Ojos brillantes",
    "Aullidos/gru&ntilde;idos",
    "Garras",
    "Colmillos",
    "Macabro",
    "Demacrado",
    "Humanoide",
    "Erguido",
    "Cuadr&uacute;pedo",
    "Andador",
    "P&aacute;jaro",
    "Centauroide",
    "Reptador",
    "Patas",
    "Sin patas",
    "Ameboides",
    "Simetr&iacute;a radial",
    "Asim&eacute;trico",
    "Pez",
    "Esf&eacute;rico",
    "Nube",
    "Intangible",
    "Cilindro",
    "C&oacute;nico",
    "Medusa",
    "Formas Geom&eacute;tricas",
    "l&iacute;quido",
    "Alado",
    "Muchos brazos",
    "Sin brazos",
    "Segmentada",
    "Rastrera",
    "reina",
    "Sirve a reina",
    "Antenas",
    "primordial",
    "salvaje",
    "extremidades",
    "Llagas",
    "Supurante",
    "Muscular",
    "resistente",
    "ojos peque&ntilde;os",
    "ojos Grandes",
    "Un ojo",
    "piel gruesa",
    "Tumores",
    "Bultos",
    "Fundas de alas",
    "iridiscente",
    "excavaci&oacute;n",
    "Sacos",
    "pus",
    "Pico",
    "garras",
    "plumas",
    "extremidades",
    "escamoso",
    "vestigial",
    "Olor agudo",
    "manadas",
    "jerarqu&iacute;as",
    "Ojos saltones",
    "colmillos",
    "bocas",
    "Cola",
    "Crueldad",
    "velocidad",
    "silencio",
    "Aletas",
    "hedor",
    "escamas",
    "hambre",
    "Espinas",
    "Enjambre",
    "v&oacute;mitos",
    "carro&ntilde;a",
    "Volador",
    "rapidez",
    "pedregoso",
    "&Oacute;rganos externos",
    "Tenazas",
    "conchas",
    "muda de piel/exoesqueleto",
    "palpadores",
    "Verrugas",
    "Suave",
    "H&uacute;medo",
    "putrefacci&oacute;n",
    "retorci&eacute;ndose",
    "royendo",
    "Hueso",
    "Veneno",
    "traici&oacute;n",
    "astucia",
    "sigilo",
    "parches de conchas",
    "Telara&ntilde;as",
    "Ojos facetados",
    "C&aacute;scaras",
    "paciencia",
    "fosforescente",
    "Tent&aacute;culos",
    "Tinta",
    "cambia de color",
    "Lengua pegajosa",
    "croar",
    "saltar",
    "quitina",
    "Caparaz&oacute;n",
    "lentitud",
    "pico que rompe",
    "madrigueras",
    "Gl&aacute;ndulas de baba",
    "Huevos",
    "Par&aacute;sitos",
    "maldad",
    "delgadez",
    "Ceguera",
    "excavaci&oacute;n",
    "descomposici&oacute;n",
    "Enrollado",
    "Mezclado con otro",
    "Cosido",
    "Mand&iacute;bulas",
    "ventosas",
    "zarcillos",
    "articulaciones",
    "Escamas",
    "Serpentinas",
    "Gelatinoso",
    "Demacrado",
    "Esquel&eacute;tico",
    "Desollado",
    "Demacrado",
    "Cori&aacute;ceo",
    "musculoso",
    "Esquel&eacute;tico",
    "niebla",
    "Mont&oacute;n",
    "amorfo",
    "Mand&iacute;bulas verticales",
    "P&uacute;as",
    "largo",
    "Plumas",
    "Derretido",
    "Vamp&iacute;rico",
    "Fl&aacute;cido",
    "Hinchado",
    "Amordazado",
    "Pelaje",
    "Obeso",
    "Chupando",
    "Prob&oacute;scide",
    "Muchas articulaciones",
    "Desollado",
    "Sin piel",
    "Aplastador",
    "Pezu&ntilde;as",
    "C&oacute;rneo",
    "Guijarros",
    "Quitinoso",
    "Hoja retr&aacute;ctil",
    "Mantis",
    "Quitinosa",
    "ar&aacute;cnido",
    "Transparentes",
    "Cuerdas",
    "Dientes",
    "Ojos telesc&oacute;picos",
    "Microcef&aacute;lico",
    "Ampollas",
    "Sin boca",
    "Boca retorcida",
    "Esf&eacute;rico",
    "Aerosol",
    "Multicabezas",
    "Saliva &aacute;cida",
    "met&aacute;lico",
]; //let ATRIBUTOS_MONSTRUOS




let HABILIDADES_MONSTRUOS = [
    "Sin habilidad especial",
    "Contacto ocular: da&ntilde;o, transformaci&oacute;n, petrificaci&oacute;n, control mental...",
    "Armadura: Resiste todos los ataques",
    "Armadura: Resiste solo algunos ataques",
    "Veloz: Dobla su n&uacute;mero de ataques/acciones/movimiento x veces.",
    "Volador",
    "Nadador/buceador",
    "Sentidos aumentados: Percibir lo invisible, predecir el futuro, etc...",
    "Ocultaci&oacute;n/camuflaje: Solo puede ser visto por c&aacute;maras, ni&ntilde;os, etc...",
    "Par&aacute;lisis: Por veneno, congelaci&oacute;n, mirada, contacto, etc...",
    "Armas naturales: Dientes, garras, taladradoras, sierras, armas...",
    "Trepador pared/techo",
    "Veneno: efectos inmediatos o graduales (da&ntilde;o, par&aacute;lisis, sue&ntilde;o, etc...)",
    "Carga: De vez en cuando puede hacer ataques cargando.",
    "Distracci&oacute;n: Luz cegadora, sonido atronador, ataque debilitador.",
    "Atrapador: Tela de ara&ntilde;a, l&iacute;quido pegajoso, tant&aacute;culos, etc...",
    "Punto d&eacute;bil: luz, agua, sustancia extra&ntilde;a, objeto, mineral, arma, etc...",
    "Sexto sentido: por ecolocalizaci&oacute;n, vibraciones, etc...",
    "Defensa extra: inmune o resistente contra un cierto tipo de ataque.",
    "Telepat&iacute;a: con otras criaturas, humanos. Con im&aacute;genes, significados...",
    "Uso limitado: Sus otras habilidades tienen uso limitado.",
    "Ataque muy potente: aliento de drag&oacute;n, toque absorbe-vida, el&eacute;ctrico...",
    "Invocador: A otras criaturas m&aacute;s/menos poderosas, m&aacute;s/menos tiempo.",
    "Inmunidad: a un cierto tipo de ataques.",
    "Control mental: Puede controlar a otro personaje.",
    "T&uacute;nel: Puede atravesar materiales, roca, paredes, etc...",
    "Ataque preciso: eficaz contra fantasmas, o muertos, o pecadores, etc...",
    "Ataque a distancia: en forma de chorro, rayo, cono, nube, etc...",
    "Teletransporte: entre lugares, dimensiones, tiempo, etc...",
    "Aterrador: hace huir, inmovilizar a la gente, etc...",
    "Absorbe la vida: el da&ntilde;o que hace es vida que recupera.",
    "Regeneraci&oacute;n/Curaci&oacute;n r&aacute;pida.",
    "Da&ntilde;o que reduce un atributo (fuerza, inteligencia, destreza, etc...)",
    "Per&iacute;metro defensivo: niebla, tinta, energ&iacute;a o aura, penalizaci&oacute;n atacantes.",
    "Incorp&oacute;reo: sin forma f&iacute;sica, es como un fantasma, sombra, etc...",
    "Animador: Animar objetos inanimados, resucitar muertos, etc...",
    "Anfibio: sobrevive en agua, espacio, vac&iacute;o, otra dimensi&oacute;n, etc...",
    "Transformaci&oacute;n: A s&iacute; mismo o a otros (vampiro, zombie, esporas)",
    "Bendecir",
    "maldecir",
    "Enmara&ntilde;ar",
    "Apresar",
    "atrapar",
    "Veneno",
    "enfermedad",
    "Paralizar",
    "petrificar",
    "Imitar",
    "forma",
    "camuflaje",
    "Seducir",
    "hipnotizar",
    "Disolver",
    "desintegrar",
    "Magia",
    "Drenar vida",
    "magia",
    "Inmunidad a Elemento",
    "Leer mentes",
    "controlar mentes",
    "Organizado",
    "Enterrado",
    "Camuflado",
    "Adivinaci&oacute;n",
    "Encantamiento",
    "Evocaci&oacute;n",
    "Ilusi&oacute;n",
    "Nigromancia",
    "Invocaci&oacute;n",
    "Extra&ntilde;o color",
    "Extra&ntilde;o olor",
    "Extra&ntilde;o sonido",
    "Geom&eacute;trico",
    "Red interconectado",
    "Cristalino",
    "v&iacute;treo",
    "F&uacute;ngico",
    "Gaseoso",
    "humeante",
    "Espejismo",
    "ilusi&oacute;n",
    "Volc&aacute;nico",
    "explosivo",
    "Magn&eacute;tico",
    "repulsivo",
    "Desprovisto de vida",
    "Inesperadamente con vida",
    "Concebidor",
    "Destructor",
    "Autarca",
    "Observador",
    "Creador",
    "Destructor",
    "Jerarca",
    "Discernido",
    "Ideador",
    "Devorador",
    "Rey",
    "Adivino",
    "Padre",
    "Devorador",
    "Se&ntilde;or",
    "Haruspex",
    "Forja",
    "Erradicador",
    "Maestro",
    "Conocedor",
    "Encarnador",
    "Devorador",
    "Pontifex",
    "Or&aacute;culo",
    "Hacedor",
    "Ravener",
    "Pr&iacute;ncipe",
    "Profeta",
    "Madre",
    "Maldidor",
    "Gobernante",
    "Vidente",
    "Fuente",
    "Arruinador",
    "Sult&aacute;n",
    "Portavoz",
    "Sediento",
    "&uacute;tero",
    "Tirano",
    "Susurrador",
    "Edad",
    "Cavernas",
    "Ciudades",
    "Fr&iacute;o",
    "Cad&aacute;veres",
    "Danza",
    "Muerte",
    "Decadencia",
    "Desiertos",
    "Enfermedad",
    "Sue&ntilde;os",
    "Tierra",
    "Fertilidad",
    "Llama",
    "Bosques",
    "Hambre",
    "Ilusiones",
    "Selvas",
    "Vida",
    "Memoria",
    "Espejos",
    "Reflejos",
    "Monta&ntilde;as",
    "M&uacute;sica",
    "Noche",
    "Dolor",
    "Par&aacute;sitos",
    "Plantas",
    "Caminos",
    "Mares",
    "Percepci&oacute;n",
    "Sensorial",
    "Serpientes",
    "Sombras",
    "Silencio",
    "Cielo",
    "Humo",
    "Niebla",
    "Hechicer&iacute;a",
    "Especie",
    "Alien&iacute;gena",
    "Animal",
    "Emoci&oacute;n",
    "Forma",
    "Sol",
    "Pantanos",
    "Sed",
    "Tiempo",
    "Alima&ntilde;as",
    "Voces",
    "Tierras",
    "Bald&iacute;as",
    "Agua",
    "Palabras",
    "Deforma la luz (puede ser invisible) ",
    "Licua el tejido animal terrestre",
    "Un aguij&oacute;n o garras t&oacute;xicas",
    "Movimiento sobre superficies s&oacute;lidas ",
    "Desaf&iacute;a la gravedad",
    "Deforma el espacio",
    "Pueden tomar la forma de humanos ",
    "Vuelan con alas",
    "Vuelan con sacos de gas",
    "Vuelan con fisonom&iacute;a alien&iacute;gena",
    "Se mueven en r&aacute;fagas de velocidad",
    "Excavan en la tierra",
    "Apuntar con precisi&oacute;n",
    "Amputador",
    "Parcialmente insustancial",
    "Rastreador",
    "Licor esclavizante",
    "Interrumpen los dispositivos electr&oacute;nicos ",
    "Fuerza tit&aacute;nica",
    "Se niegan a morir",
    "Teletransporte",
    "Tres ataques por ronda",
    "Vomitan sustancia nociva",
    "Reflejos asombrosos",
    "Susurros horrorosos",
    "Incendiario",
    "Congelador",
    "Radioactivo",
    "T&oacute;xico",
]; //let HABILIDADES_MONSTRUOS = [





function print_monstruos(element_id) {
    var element = document.getElementById(element_id);
    if (!element) return;

    let clase_monstruo = random_from_list(CLASE_MONSTRUO);

    let monstruo_text = clase_monstruo;

    let monstruo_attribute;
    let other_class;

    for (let i=0; i<2; i++) {
        monstruo_text += '<br/>' + random_from_list(ATRIBUTOS_MONSTRUOS);
    } //for (let i=0; i<2; i++) {

    var html_code = "";
    html_code += print_fortune_cookie(monstruo_text);
    html_code += '<br/>';
    html_code += compute_fortunes(HABILIDADES_MONSTRUOS, 2);
    html_code += '<br/>';
    html_code += compute_fortunes(ADJETIVOS_LOVECRAFT, 2);
    element.innerHTML = html_code;
    element.scrollTop = "0";
} //function print_monstruos(element_id)
