
var PISTAS_1 = [
    "Alfombra",
    "Fotograf&iacute;as",
    "Informe",
    "Reloj de pulsera",
    "Diario",
    "Pistola",
    "Certificados de acciones",
    "Regalos",
    "Lista de invitados",
    "Florero",
    "Carta de amor",
    "Demanda de dinero",
    "Arete de diamantes",
    "Serie de n&uacute;meros",
    "Peri&oacute;dico",
    "Informe",
    "policial",
    "Bote de pastillas",
    "Piezas de ajedrez",
    "T&iacute;tulo de propiedad",
    "Dedo humano",
    "Lencer&iacute;a",
    "Permiso de construcci&oacute;n",
    "Disfraz",
    "Veneno",
    "Libro",
    "Contrato",
    "Cuchillo",
    "Invitaci&oacute;n a Fiesta",
    "Tarjeta Embarque",
    "Esposas",
    "Fusta",
    "Guantes de cuero",
    "Anuario",
    "T&uacute;nel/pasaje secreto",
    "vestido/traje",
    "Oferta de trabajo",
    "Dados cargados",
    "Cartas marcadas",
    "Licor del error",
    "Licor del acierto",
    "Disfraz del Diablo",
    "Atlas del Infierno",
    "Barrera",
    "Concurso",
    "Tarea",
    "Misterio",
    "Lucha",
    "Negociaci&oacute;n",
    "Trampa",
    "Resistencia",
    "Persecuci&oacute;n",
    "Amenaza",
    "Debate",
    "Diente",
    "Dentadura",
    "Rompecabezas",
    "Llave",
    "ganz&uacute;a",
    "Baratija",
    "Poci&oacute;n",
    "comida",
    "Pintura",
    "ceramica",
    "Ropajes",
    "capa",
    "Anillo",
    "guantes",
    "Jarra",
    "vasija",
    "copa",
    "Alfombra",
    "tapete",
    "Cesta",
    "caj&oacute;n",
    "cofre",
    "Estatuilla",
    "&iacute;dolo",
    "Instrumento",
    "herramienta",
    "Bandera",
    "estandarte",
    "Libro",
    "pergamino",
    "Pulsera",
    "brazalete",
    "Arma",
    "bast&oacute;n",
    "varita",
    "Colgante",
    "amuleto",
    "Armadura",
    "escudo",
    "yelmo",
    "Cintur&oacute;n",
    "arn&eacute;s",
    "Espejo",
    "reloj",
    "reloj de arena",
    "Sombrero",
    "m&aacute;scara",
    "Mascota",
    "montura",
    "Orbe",
    "sello",
    "b&aacute;culo",
    "Aparato",
    "constructo",
    "Corona",
    "cetro",
    "Nota",
    "Una sustancia extra&ntilde;a y pegajosa",
    "&Uacute;ltima voluntad y testamento",
    "Un mapa de un lugar",
    "Una ubicaci&oacute;n tiene una flecha escrita a mano",
    "Unas hojas de papel llenas de",
    "Una llave, grabada con",
    "Una prenda desgarrada, manchada de",
    "Un miembro amputado",
    "Una extremidad amputada",
    "Una cabeza amputada",
    "Un olor extra&ntilde;o en el aire",
    "Una estatuilla misteriosa",
    "Un joyero",
    "Una mu&ntilde;eca",
    "Una piedra",
    "Una moneda",
    "Una urna",
    "Pertenencias",
    "Suministros",
    "Mochila que parece",
    "Alguien est&aacute;",
    "La canci&oacute;n",
    "Un cabello de aspecto",
    "Un mech&oacute;n de pelo",
    "Un viejo cuchillo",
    "Un rev&oacute;lver",
    "Casquillos de",
    "Cuerda",
    "Huellas",
    "Manchas de sangre",
    "Una runa",
    "Un muerto",
    "Un viejo juguete de madera con el que jugabas de ni&ntilde;o",
    "Huellas de llantas de auto",
    "Una nota con solo el nombre de la ciudad cercana escrita",
    "Una cuerda colgando desde arriba",
    "Una tumba que ha sido excavada",
    "Una linterna rota",
    "Una trampa para osos",
    "Un hombre cantando",
    "Un rastro claro donde algo grande ha sido arrastrado",
    "Un viento helado",
    "Un mapa de un laberinto",
    "Una carta de recomendaci&oacute;n",
    "El sonido de cristales rompi&eacute;ndose",
    "Disparos en la distancia",
    "Un trozo de c&aacute;scara",
    "Libro donde ciertos eventos se han tachado desordenadamente",
    "Una botella de licor vac&iacute;a",
    "Ropa, rasgada y desgarrada",
    "Un reloj destrozado",
    "Un reloj que anda al rev&eacute;s",
    "Una reliquia antigua",
]; //var PISTAS_1 = [


var PISTAS_2 = [
    "Ensangrentado",
    "Descartado",
    "Postizo",
    "Plastificado",
    "Extravagante",
    "Desfigurado",
    "Antiguo",
    "Caro",
    "Manchado de sangre",
    "Enterrado",
    "Desenterrado",
    "Robado",
    "Falso/falsificado",
    "Destrozado/arrancado",
    "Viejo",
    "Fangoso/sucio",
    "Duplicado",
    "Desgastado/hecho",
    "andrajos",
    "Desaparecido",
    "Exquisito",
    "Corrupto/alterado",
    "Mordido",
    "Arrugado/aplastado",
    "Triturado/rasgado",
    "Viejo/antiguo",
    "Inesperado",
    "Descolorido/gastado",
    "Nuevo/pr&iacute;stino",
    "Envuelto para regalo",
    "Oculto/secreto",
    "Inundado",
    "Quemado",
    "Envuelto",
    "Masticado",
    "Inexplicable",
    "que hab&iacute;as olvidado",
    "que ten&iacute;as de peque&ntilde;o",
    "con marcas sospechosas",
    "salpicada",
    "cortada con una navaja",
    "desechado",
    "oxidado",
    "con muescas",
    "atrapado",
    "extra&ntilde;o",
    "en plena naturaleza",
    "te persigue",
    "cantando una canci&oacute;n extra&ntilde;a",
    "saqueada",
    "saqueada por alg&uacute;n tipo de bestia",
    "desgarrado",
    "con cenizas",
    "extra&ntilde;a",
    "perfectamente esf&eacute;rica",
    "infantil",
    "vac&iacute;o pero adornado",
    "sangre",
    "extra&ntilde;os glifos",
    "dejada por un amigo",
    "dejada por un amigo profesor",
    "que emite un olor extra&ntilde;o e inidentificable",
    "en sobre cerrado",
    "que nunca has visto antes",
    "con la palabra Aqu&iacute; al lado",
    "s&iacute;mbolos indescifrables",
]; //var PISTAS_2 = [




function print_pistas(element_id) {
    var element = document.getElementById(element_id);
    if (!element) return;

    var html_code = "";

    let pista_text = random_from_list(PISTAS_1);
    pista_text += '<br/>' + random_from_list(PISTAS_2);
    html_code += print_fortune_cookie(pista_text);

    element.innerHTML = html_code;
    element.scrollTop = "0";
} //function print_pistas(element_id)
