let NOMBRES_PNJ = [
    "Chris",
    "Marvin",
    "Amanda",
    "Scott",
    "Jane",
    "David",
    "Melanie",
    "Milton",
    "Melody",
    "Larissa",
    "Gordon",
    "Emily",
    "June",
    "Sara",
    "Andrew",
    "Sandy",
    "Sue",
    "Sally",
    "Albert",
    "Buck",
    "Jenny",
    "Heath",
    "Eleanor",
    "Timothy",
    "Penelope",
    "Frederick",
    "Elena",
    "Cyrus",
    "Edmund",
    "Tara",
    "Donna",
    "George",
    "Stephen",
    "Marcus",
    "Sam",
    "Tabitha",
    "Adric",
    "Aldo",
    "Amosen",
    "Andrel",
    "Arden",
    "Arlyn",
    "Arquo",
    "Arvus",
    "Ashlyn",
    "Branon",
    "Brace",
    "Brance",
    "Brena",
    "Ladrillos",
    "Candra",
    "Carissa",
    "Carro",
    "Casslyn",
    "Cavelle",
    "Clave",
    "Corille",
    "Cross",
    "Crowl",
    "Cyrene",
    "Daphnia",
    "Drav",
    "Edlun",
    "Emeline",
    "Grine",
    "Helles",
    "Hix",
    "Holtz",
    "Kamelin",
    "Kelyr",
    "Kobb",
    "Kristov",
    "Laudius",
    "Lauria",
    "Lenia",
    "Lizete",
    "Lorette",
    "Lucella",
    "Lynthia",
    "Mara",
    "Milos",
    "Morlan",
    "Myre",
    "Narcus",
    "Naria",
    "Noggs",
    "Odrienne",
    "Orlan",
    "Phin",
    "Polonia",
    "Quess",
    "Remira",
    "Ring",
    "Roethe",
    "Sesereth",
    "Sethla",
    "Skannon",
    "Stavrul",
    "Stev",
    "Syra",
    "Talitha",
    "Tesslyn",
    "Thena",
    "Timoth",
    "Tocker",
    "Unha",
    "Vaurin",
    "Veleris",
    "Veretta",
    "Vestine",
    "Vey",
    "Volette",
    "Vond",
    "Weaver",
    "Wester",
    "Zamira",
    "Abby",
    "Akai",
    "Binh",
    "Vadim",
    "Pavel",
    "Yolanda",
    "Brittney",
    "Morgan",
    "Sally",
    "Mary Joe",
    "Helen",
    "Elizabeth",
    "Florence",
    "Galina",
    "Mabel",
    "Rose",
    "Lara",
    "Cora",
    "Josephine",
    "Georgia",
    "Chin",
    "Jane",
    "Anastasia",
    "Ayako",
    "Cameron",
    "Onya",
    "Abby",
    "Emerald",
    "Ginger",
    "Harper",
    "Nala",
    "Sabrina",
    "Elena",
    "Victoria",
    "Julie",
    "Piper",
    "Lana",
    "Ashley",
    "Akhil",
    "Marissa",
    "Bosede",
    "Tara",
    "Ajit",
    "Masika",
    "Marie",
    "F&aacute;tima",
    "Lena",
    "Julie",
    "Elise",
    "Chloe",
    "Emma",
    "Emilija",
    "Peter",
    "Oscar",
    "Lawrence",
    "Abioye",
    "Frederick",
    "Aravind",
    "Leroy",
    "Hugh",
    "Alice",
    "Leslie",
    "Percy",
    "Alex",
    "Lakshmana",
    "Morris",
    "Keung",
    "Jitinder",
    "Matthew",
    "Chetana",
    "Amanda",
    "Felix",
    "Jake",
    "Claud",
    "Steve",
    "Simon",
    "Christopher",
    "Dayo",
    "Akua Jerome",
    "Augustus",
    "Conrad",
    "Akai",
    "Aran",
    "Hiro",
    "Ichiro",
    "Jing",
    "Ronin",
    "Katya",
    "Faraji",
    "Pierre",
    "Tam",
    "Lukas",
    "Noah",
    "Theo",
    "Jonas",
    "Dominic",
    "Diego",
    "Jack",
    "William",
    "Tanvir",
    "Leon",
    "Neema",
    "Elias",
    "Arthur",
    "Jaoquin",
    "Carter",
    "Samual",
    "Logan",
    "Jacob",
    "Finbar",
    "Hywn",
    "Un Ojo",
    "Alhoro",
    "Arlon",
    "Yev",
    "Slime",
    "Jocat",
    "Ewing",
    "Lim",
    "Poy",
    "Milo",
    "Deryl",
    "Medlyn",
    "Astrafel",
    "Daelwyn",
    "Feliana",
    "Damarra",
    "Sistranalle",
    "Pendrell",
    "Melliandre",
    "Dagoliir",
    "Baldric",
    "Leena",
    "Dunwick",
    "Willem",
    "Edwyn",
    "Florian",
    "Seraphine",
    "Quorra",
    "Charlotte",
    "Lily",
    "Ramonde",
    "Cassandra",
    "Durga",
    "Aelfar",
    "Gerda",
    "Rurgosh",
    "Bjorn",
    "Drummond",
    "Helga",
    "Siggrun",
    "Freya",
    "Wesley",
    "Brinton",
    "Jon",
    "Sara",
    "Hawthorn",
    "Elise",
    "Clarke",
    "Lenore",
    "Piotr",
    "Dahlia",
    "Carmine",
    "Hycorax",
    "Ethanwe",
    "Sinathel",
    "Demanor",
    "Menoliir",
    "Mithralan",
    "Taeros",
    "Aegor",
    "Tanner",
    "Dunstan",
    "Rose",
    "Ivy",
    "Robard",
    "Mab",
    "Thistle",
    "Puck",
    "Anne",
    "Serah",
    "Elana",
    "Obelis",
    "Herran",
    "Syla",
    "Andanna",
    "Siobhan",
    "Aziz",
    "Pelin",
    "Sibel",
    "Nils",
    "Wei",
    "Ozruk",
    "Surtur",
    "Brunhilda",
    "Annika",
    "Janos",
    "Greta",
    "Dim",
    "Rundrig",
    "Jarl",
    "Xotoq",
    "Elohiir",
    "Sharaseth",
    "Hasrith",
    "Shevaral",
    "Cadeus",
    "Eldar",
    "Kithracet",
    "Thelian",
    "Finnegan",
    "Olive",
    "Randolph",
    "Bartleby",
    "Aubrey",
    "Baldwin",
    "Becca",
    "Hawke",
    "Rudiger",
    "Gregor",
    "Brianne",
    "Walton",
    "Agoston",
    "Abigel",
    "Arpad",
    "Aliz",
    "Attila",
    "Amalia",
    "Bognar",
    "Andrea",
    "Denes",
    "Aranka",
    "Edmond",
    "Csilla",
    "Erno",
    "Edit",
    "Etele",
    "Erzebet",
    "Ferdind",
    "Gertrud",
    "Florian",
    "Greta",
    "Geza",
    "Iren",
    "Gyula",
    "Kamilla",
    "Hugo",
    "Lara",
    "Karcsi",
    "Lia",
    "Konrad",
    "Lujza",
    "Lazlo",
    "Matild",
    "Lukas",
    "Olga",
    "Marko",
    "Otilia",
    "Miklos",
    "Panna",
    "Peti",
    "Roza",
    "Robi",
    "Terez",
    "Tamas",
    "Tunda",
    "Ronold",
    "Valeria",
    "Viktor",
    "Vilma",
    "Zoltan",
    "Viola",
    "Adibemi",
    "Abeni",
    "Aboye",
    "Ade",
    "Adegoke",
    "Alaba",
    "Ayokun",
    "Bolanle",
    "Babajide",
    "Bosade",
    "Batunde",
    "Daraja",
    "Enitan",
    "Fari",
    "Femi",
    "Gbemis",
    "Kayin",
    "Ife",
    "Kayode",
    "Ige",
    "Lanre",
    "Lewa",
    "Lekan",
    "Mojisola",
    "Mongo",
    "Monifa",
    "Nwachuk",
    "Olufemi",
    "Oban",
    "Omolara",
    "Ogun",
    "Oni",
    "Olukayo",
    "Orisa",
    "Oluwala",
    "Osa",
    "Oluwato",
    "Ronke",
    "Onipede",
    "Shanum",
    "Sijuade",
    "Simisola",
    "Toben",
    "Titlayo",
    "Utiba",
    "Yejide",
    "Zaki",
    "Yewand",
    "Zoputan",
    "Zauna",
    "Aatami",
    "Aija",
    "Armas",
    "Aina",
    "Arsi",
    "Ainikki",
    "Arvi",
    "Heini",
    "Eetu",
    "Ilona",
    "Hannu",
    "Irja",
    "Heimo",
    "Jaana",
    "Ilkka",
    "Kirsi",
    "Jorma",
    "Maija",
    "Kaapo",
    "Marita",
    "Kain",
    "Miina",
    "Kauko",
    "Mimmi",
    "Lari",
    "Minja",
    "Manu",
    "Mira",
    "Nuutti",
    "Naemi",
    "Petri",
    "Outi",
    "Raimo",
    "Pirjo",
    "Reima",
    "Paivikki",
    "Risto",
    "Riikka",
    "Sakari",
    "Saimi",
    "Sampsa",
    "Suoma",
    "Seppo",
    "Suvi",
    "Taito",
    "Tuula",
    "Terho",
    "Vellamo",
    "Vilppu",
    "Virpi",
    "Ade",
    "Adah",
    "Adi",
    "Bulan",
    "Amaziah",
    "Candra",
    "Ayokun",
    "Devi",
    "Ary",
    "Hanjojo",
    "Banbang",
    "Iman",
    "Bima",
    "Intan",
    "Budi",
    "Laksmin",
    "Darma",
    "Lestari",
    "Dian",
    "Limjato",
    "Eli",
    "Marah",
    "Gunardi",
    "Mewati",
    "Hartono",
    "Melati",
    "Irwan",
    "Nadiyya",
    "Lauwita",
    "Ophrah",
    "Masama",
    "Ramza",
    "Okan",
    "Saphira",
    "Onsimus",
    "Selah",
    "Sammin",
    "Sumiten",
    "Tameem",
    "Tamar",
    "Tanaya",
    "Tanjaya",
    "Tirto",
    "Tjokro",
    "Wiryono",
    "Tri",
    "Yandi",
    "Wangi",
    "Zebulun",
    "Zenze",
    "Agune",
    "Beatrice",
    "Breagan",
    "Bronwyn",
    "Cannora",
    "Drelil",
    "Elgile",
    "Esme",
    "Groua",
    "Henaine",
    "Lirann",
    "Lirathil",
    "Lisabeth",
    "Moralil",
    "Morgwen",
    "Sybil",
    "Theune",
    "Wenlan",
    "Ygwal",
    "Yslen",
    "Arwel",
    "Bevan",
    "Boroth",
    "Borrid",
    "Breagle",
    "Breglor",
    "Canhoreal",
    "Emrys",
    "Ethex",
    "Gringle",
    "Grinwit",
    "Gruwid",
    "Gruwth",
    "Gwestin",
    "Mannog",
    "Melnax",
    "Orthax",
    "Triunein",
    "Wenlan",
    "Yirmeor",
    "Aurora",
    "Mena",
    "Binah",
    "Ocre",
    "Coral",
    "Ovya",
    "Hassu",
    "Porfirio",
    "Iris",
    "Vitra",
    "Kali",
    "Zafiro",
    "Amit",
    "Lorenzo",
    "Antonieta",
    "Magdalena",
    "Beena",
    "Malia",
    "Celina",
    "Perceval",
    "Damba",
    "Radcliffe",
    "Dardellyon",
    "Ursulina",
    "Naturales",
    "Aren",
    "Laurel",
    "Bellota",
    "Ortiga",
    "Brisa",
    "Polilla",
    "Cedro",
    "R&iacute;o",
    "Cervatillo",
    "Selena",
    "Cuento",
    "ZarzaChaaya",
    "Neva",
    "Ceniza",
    "Noviembre",
    "Cuervo",
    "Orpheo",
    "Dunn",
    "Spindle",
    "Eco",
    "Tamala",
    "Morgan",
    "Umber",
    "Ahe",
    "Gulru",
    "Blaise",
    "Jiniya",
    "Blush",
    "Lalitya",
    "Brisa",
    "Mridul",
    "Cecile",
    "Naila",
    "Chul",
    "Sanura",
    "Ancla",
    "Marzo",
    "Bryn",
    "Montez",
    "Cierra",
    "Pierce",
    "Folke",
    "Rigg",
    "Kiva",
    "Salim",
    "Latrice",
    "Sunder",
]; //let NOMBRES_PNJ = [





let APELLIDOS_PNJ = [
    "Jensen",
    "Nyman",
    "Bayer",
    "O-Sullivan",
    "Ahmed",
    "Dawson",
    "Schneider",
    "Aliyev",
    "Bolkvadze",
    "Jeon",
    "Kozlov",
    "Brown",
    "Davis",
    "Anderson",
    "Harris",
    "Alonso",
    "Thomson",
    "Lovric",
    "Johansen",
    "Garc&iacute;a",
    "Mart&iacute;nez",
    "Robinson",
    "Niemi",
    "DeBoer",
    "Clark",
    "Rodr&iacute;guez",
    "Lewis",
    "Costa",
    "Walker",
    "Patel",
    "Moshe",
    "Young",
    "Hern&aacute;ndez",
    "Watanabe",
    "Flores",
    "Romero",
    "Wright",
    "L&oacute;pez",
    "D&iacute;az",
    "Mercier",
    "Dey",
    "Scott",
    "Green",
    "Carter",
    "Omer",
    "P&eacute;rez",
    "Edwards",
    "Stewart",
    "S&aacute;nchez",
    "Reed",
    "Leon",
    "Cook",
    "Morgan",
    "Eriksson",
    "Babayev",
    "Brooks",
    "Sanders",
    "Zhōu",
    "Dubois",
    "Bennett",
    "Matsui",
    "Gruber",
    "Berger",
    "Dupont",
    "Crawford",
    "Gāo",
    "Boyd",
    "Novikov",
    "Ferguson",
    "Mohammed",
    "Long",
    "Yim",
    "Petrov",
    "Petridis",
    "Cohen",
    "Shibata",
    "Nakagawa",
    "Ali",
    "Marino",
    "Han",
    "Yu",
    "Khan",
    "Cruz",
    "De Luca",
    "V&aacute;zquez",
    "Rivera",
    "Wong",
    "Xim&eacute;nez",
    "Silva",
    "Blanchette",
    "Ankhayat",
    "Arran",
    "Athanoch",
    "Basran",
    "Boden",
    "Booker",
    "Bowman",
    "Breakiron",
    "Brogan",
    "Clelland",
    "Clermont",
    "Coleburn",
    "Comber",
    "Daava",
    "Dalmore",
    "Danfield",
    "Dunvil",
    "Farros",
    "Grine",
    "Haig",
    "Helker",
    "Helles",
    "Hellyers",
    "Jayan",
    "Jeduin",
    "Kardera",
    "Karstas",
    "Keel",
    "Kessarin",
    "Kinclaith",
    "Lomond",
    "Maroden",
    "Michter",
    "Morriston",
    "Penderyn",
    "Prichard",
    "Rowan",
    "Sevoy",
    "Skelkallan",
    "Skora",
    "Slane",
    "Strangford",
    "Strathmill",
    "Templeton",
    "Tyrconnell",
    "Vale",
    "Walund",
    "Welker",
    "Armstrong",
    "Blair",
    "Blair",
    "Boosh",
    "Cassidy",
    "Creel",
    "Darlington",
    "Deschain",
    "Finch",
    "Fletcher",
    "Greaves",
    "Hardaway",
    "Harper",
    "Hendricks",
    "Hill",
    "Jackson",
    "Jacobs",
    "Kennedy",
    "Krause",
    "Lamb",
    "Laughton",
    "Leaf",
    "Ludlow",
    "Mellon",
    "Newman",
    "Nicholson",
    "Montauk",
    "Ripley",
    "Sullivan",
    "Summers",
    "Thompson",
    "Thune",
    "Turlington",
    "White",
    "Willoughby",
    "York",
    "Agoston",
    "Abigel",
    "Arpad",
    "Aliz",
    "Attila",
    "Amalia",
    "Bognar",
    "Andrea",
    "Denes",
    "Aranka",
    "Edmond",
    "Csilla",
    "Erno",
    "Edit",
    "Etele",
    "Erzebet",
    "Ferdind",
    "Gertrud",
    "Florian",
    "Greta",
    "Geza",
    "Iren",
    "Gyula",
    "Kamilla",
    "Hugo",
    "Lara",
    "Karcsi",
    "Lia",
    "Konrad",
    "Lujza",
    "Lazlo",
    "Matild",
    "Lukas",
    "Olga",
    "Marko",
    "Otilia",
    "Miklos",
    "Panna",
    "Peti",
    "Roza",
    "Robi",
    "Terez",
    "Tamas",
    "Tunda",
    "Ronold",
    "Valeria",
    "Viktor",
    "Vilma",
    "Zoltan",
    "Viola",
    "Adibemi",
    "Abeni",
    "Aboye",
    "Ade",
    "Adegoke",
    "Alaba",
    "Ayokun",
    "Bolanle",
    "Babajide",
    "Bosade",
    "Batunde",
    "Daraja",
    "Enitan",
    "Fari",
    "Femi",
    "Gbemis",
    "Kayin",
    "Ife",
    "Kayode",
    "Ige",
    "Lanre",
    "Lewa",
    "Lekan",
    "Mojisola",
    "Mongo",
    "Monifa",
    "Nwachuk",
    "Olufemi",
    "Oban",
    "Omolara",
    "Ogun",
    "Oni",
    "Olukayo",
    "Orisa",
    "Oluwala",
    "Osa",
    "Oluwato",
    "Ronke",
    "Onipede",
    "Shanum",
    "Sijuade",
    "Simisola",
    "Toben",
    "Titlayo",
    "Utiba",
    "Yejide",
    "Zaki",
    "Yewand",
    "Zoputan",
    "Zauna",
    "Aatami",
    "Aija",
    "Armas",
    "Aina",
    "Arsi",
    "Ainikki",
    "Arvi",
    "Heini",
    "Eetu",
    "Ilona",
    "Hannu",
    "Irja",
    "Heimo",
    "Jaana",
    "Ilkka",
    "Kirsi",
    "Jorma",
    "Maija",
    "Kaapo",
    "Marita",
    "Kain",
    "Miina",
    "Kauko",
    "Mimmi",
    "Lari",
    "Minja",
    "Manu",
    "Mira",
    "Nuutti",
    "Naemi",
    "Petri",
    "Outi",
    "Raimo",
    "Pirjo",
    "Reima",
    "Paivikki",
    "Risto",
    "Riikka",
    "Sakari",
    "Saimi",
    "Sampsa",
    "Suoma",
    "Seppo",
    "Suvi",
    "Taito",
    "Tuula",
    "Terho",
    "Vellamo",
    "Vilppu",
    "Virpi",
    "Ade",
    "Adah",
    "Adi",
    "Bulan",
    "Amaziah",
    "Candra",
    "Ayokun",
    "Devi",
    "Ary",
    "Hanjojo",
    "Banbang",
    "Iman",
    "Bima",
    "Intan",
    "Budi",
    "Laksmin",
    "Darma",
    "Lestari",
    "Dian",
    "Limjato",
    "Eli",
    "Marah",
    "Gunardi",
    "Mewati",
    "Hartono",
    "Melati",
    "Irwan",
    "Nadiyya",
    "Lauwita",
    "Ophrah",
    "Masama",
    "Ramza",
    "Okan",
    "Saphira",
    "Onsimus",
    "Selah",
    "Sammin",
    "Sumiten",
    "Tameem",
    "Tamar",
    "Tanaya",
    "Tanjaya",
    "Tirto",
    "Tjokro",
    "Wiryono",
    "Tri",
    "Yandi",
    "Wangi",
    "Zebulun",
    "Zenze",
    "Abernathy",
    "Addercap",
    "Burl",
    "Candlewick",
    "Cormick",
    "Crumwaller",
    "Dunswallow",
    "Getri",
    "Glass",
    "Harkness",
    "Harper",
    "Loomer",
    "Malksmilk",
    "Smythe",
    "Sunderman",
    "Swinney",
    "Thatcher",
    "Tolmen",
    "Weaver",
    "Wolder",
]; //let APELLIDOS_PNJ = [




let APODOS_PNJ = [
    "Abedul",
    "Adicto",
    "Aguja",
    "Anillo",
    "Aparejo",
    "Artillero",
    "Asa",
    "Bicho",
    "Bobina",
    "Bollo",
    "Campana",
    "Canci&oacute;n",
    "Cardo",
    "Carill&oacute;n",
    "Cruz",
    "Cuervo",
    "Desollador",
    "Eco",
    "Escarcha",
    "Espina",
    "Espuela",
    "Gancho",
    "Grillo",
    "Ladrillos",
    "L&aacute;tigo",
    "Luna",
    "Martillo",
    "Mimbre",
    "Niebla",
    "Ogro",
    "Pedernal",
    "Plata",
    "Rana",
    "Reserva",
    "Rub&iacute;",
    "Tic-tac",
    "U&ntilde;a",
    "Doces",
    "Anginu (Viento del Norte)",
    "Api (Llamarada)",
    "Bakat (Alegr&iacute;a)",
    "Bakti (Leal)",
    "Beruntung (Afortunado)",
    "Bilah (Espada)",
    "Biru (Azul)",
    "Gemetar (Carcaj)",
    "Guntur (Trueno)",
    "Hidungi (Hocico Negro)",
    "Janda (Enlutado)",
    "Kakicerah (Trote Alegre)",
    "Kakiring (Trote Ligero)",
    "Keriangan (Rayo de Sol)",
    "Kunang (Luci&eacute;rnaga)",
    "Lapar (Ansioso)",
    "Murni (Puro)",
    "Paruh (Calderilla)",
    "Penebus (Vengador)",
    "Penyelemat (Salvador)",
    "Prajurit (Guerrero)",
    "Rusak (Quebrantado)",
    "Satucep (El Veloz)",
    "Setia (Coraz&oacute;n Puro)",
    "Tahanla (Resistente)",
    "Aave (Fantasma)",
    "Enkeli (&Aacute;ngel)",
    "Haiva (Sombra)",
    "Hopea (Plata)",
    "Ilmavirta (Corriente)",
    "Kesi (Manso)",
    "Kestaba (Resistente)",
    "Kiukuinnen (Furioso)",
    "Lansiviima (Viento del Oeste)",
    "Luotettava (Confiable)",
    "Myrskyisa (Tempestuoso)",
    "Nokka (Calderilla)",
    "Noyra (Modesto)",
    "Pitkanena (Narizotas)",
    "Saikki (Asustadizo)",
    "Salama (Trueno)",
    "Sankari (H&eacute;roe)",
    "Sisko (Hermana)",
    "Upea (Magnificente)",
    "Vahva (Fuerte)",
    "Valkoinen (Blanco)",
    "Varmaotteinen (Paso Firme)",
    "Vesuri (Segador)",
    "Vinha (R&aacute;pido)",
    "Ystava (Amigo)",
    "Adiitu (Misterio)",
    "Alayo (Feliz)",
    "Atale (Rojizo)",
    "Bilu (Calderilla)",
    "Dudupatak (Pezu&ntilde;a Oscura)",
    "Egun (Zarzamora)",
    "Eniyan (Ascua)",
    "Esirun (Pataslargas)",
    "Fenuko (Beso)",
    "Funfungo (Melena Blanca)",
    "Gunirun (Melena Larga)",
    "Imole (Brillante)",
    "Imole Uju (Ojos Brillantes)",
    "Ira (Andariego)",
    "Itan (Cuento)",
    "Iyebiye (Tesoro)",
    "Lulu (Polvareda)",
    "Nilera (Sanote)",
    "Ogbo (Moteado)",
    "Ogboju (Coraz&oacute;n Bravo)",
    "Ojiji (Sombra)",
    "Oluto (Leal)",
    "Orisa (Primavera)",
    "Orum (Cielo)",
    "Sare (Destello)",
    "Barat (Amigo)",
    "Barsony (Terciopelo)",
    "Edesem (Dulzura)",
    "Egatz (Meteoro)",
    "Eso (Lluvia)",
    "Fakyla (Antorcha)",
    "Feketsor (Cringr&iacute;s)",
    "Felho (Nube)",
    "Flotta (Flota)",
    "Gazda (Amo)",
    "Hold (Luna)",
    "Igaslo (Jamelgo)",
    "Ijeda (Asustadizo)",
    "Koszalo (Andariego)",
    "Megmento (Salvador)",
    "Napfen (Rayo de Sol)",
    "Rozsa (Rosa)",
    "Szamla (Calderilla)",
    "Szellem (Hechizado)",
    "Szeplok (Pecas)",
    "Szerence (Afortunado)",
    "Tusko (pisot&oacute;n)",
    "Vad (Ind&oacute;mito)",
    "Vihar (Tormenta)",
    "Villam (Rel&aacute;mpago)",
]; //let APODOS_PNJ = [




let PROFESIONES_PNJ = [
    "Panadero",
    "Barbero",
    "Herrero",
    "Cervecero",
    "Carnicero",
    "Carpintero",
    "Carretero",
    "Velero",
    "Tendero",
    "Estafador",
    "Tahur",
    "Contrabandista",
    "Extorsionador",
    "Zapatero",
    "Tonelero",
    "Agricultor",
    "Conductor",
    "Tintorero",
    "Bordador",
    "Pescadero",
    "Gondolero",
    "Guardia",
    "Marroquinero",
    "Alba&ntilde;il",
    "Mercader",
    "Tejero",
    "Cordelero",
    "Tapicero",
    "Sirviente",
    "Barquero",
    "Delincuente",
    "Sastre",
    "Curtidor",
    "Inventor",
    "Vendedor",
    "Tejedor",
    "Ebanista",
    "Pastor de animales",
    "Mensajero",
    "Marinero",
    "Abogado",
    "Arquitecto",
    "Artista",
    "Autor",
    "Alguacil",
    "Apicultor",
    "Banquero",
    "Cazarrecompensas",
    "Relojero",
    "Cortesano",
    "Peletero",
    "Soplador de vidrio",
    "Diplom&aacute;tico",
    "Carcelero",
    "Joyero",
    "Sanguijuela",
    "Cerrajero",
    "Magistrado",
    "M&uacute;sico",
    "M&eacute;dico",
    "Fontanero",
    "Impresor",
    "Erudito",
    "Escribano",
    "Chispas",
    "Recaudador",
    "Tesorero",
    "Susurro",
    "Compositor",
    "Mayordomo",
    "Recaudador de impuestos",
    "Capit&aacute;n",
    "Guardi&aacute;n",
    "espiritual",
    "Periodista",
    "Explorador",
    "Juntarra&iacute;les",
    "Soldado",
    "Primo",
    "Sobrino",
    "Gerente",
    "Camarero",
    "Alcalde",
    "M&iacute;stico",
    "Hijo/a",
    "Tendero",
    "Agente",
    "M&eacute;dico",
    "Maestro",
    "Dependiente",
    "Juez",
    "Costurera/Sastre",
    "televisi&oacute;n",
    "Hermano",
    "Residente",
    "Cajero",
    "Cazador",
    "Caza fantasmas",
    "Limpiador de plagas",
    "Caza Alima&ntilde;as",
    "Bibliotecario",
    "C&oacute;nyuge",
    "Socio",
    "comercial",
    "Cient&iacute;fico",
    "Banquero",
    "Residente",
    "Pescador",
    "Sacerdote",
    "hermano/cu&ntilde;ada",
    "Empresario",
    "Mayordomo",
    "asistente",
    "Ni&ntilde;o",
    "Fot&oacute;grafo",
    "Hotelero",
    "Historiador",
    "Empleado",
    "gasolinera",
    "Borracho",
    "Barista",
    "Conserje",
    "Asesino",
    "Medium",
    "Justiciero",
    "Or&aacute;culo",
    "Mercader de Mercanc&iacute;as secretas",
    "Proveedor",
    "Mercader de Materias primas",
    "Mercader de Grano",
    "Mercader de ganado",
    "Mercader de Cerveza",
    "Mercader de vino",
    "Mercader de licor",
    "Mercader de Ropa",
    "Mercader de joyer&iacute;a",
    "Mercader de Armas",
    "Mercader de armadura",
    "Mercader de Especias",
    "Mercader de tabaco",
    "Mercader de Mano de obra",
    "Mercader de esclavos",
    "Mercader de Libros",
    "Mercader de pergaminos",
    "Mercader de Ingredientes m&aacute;gicos",
    "Mercader de objetos m&aacute;gicos",
    "Bandido",
    "forajido",
    "rufi&aacute;n",
    "Ladr&oacute;n",
    "Guardaespaldas",
    "mat&oacute;n",
    "Ratero",
    "Traficante",
    "perista",
    "Estafador",
    "Lugarteniente",
    "Jefazo",
    "Ama de casa",
    "esposo",
    "Cazador",
    "recolector",
    "Granjero",
    "pastor",
    "Jornalero",
    "sirviente",
    "Cochero",
    "portero",
    "gu&iacute;a",
    "Marinero",
    "soldado",
    "guardia",
    "Clero",
    "monje",
    "Aprendiz",
    "aventurero",
    "Zapatero",
    "peletero",
    "sastre",
    "Tejedor",
    "canastero",
    "Alfarero",
    "carpintero",
    "Pe&oacute;n",
    "repostero",
    "candelero",
    "Tonelero",
    "carretero",
    "Curtidor",
    "cordelero",
    "Herrero",
    "hojalatero",
    "Mozo de cuadra",
    "herborista",
    "Viticultor",
    "joyero",
    "Posadero",
    "tabernero",
    "Artista",
    "actor",
    "juglar",
    "Armero",
    "Enterrador",
    "Erudito",
    "sabio",
    "mago",
    "Escritor",
    "ilustrador de c&oacute;dices",
    "Perfumista",
    "Arquitecto",
    "ingeniero",
    "Cerrajero",
    "relojero",
    "Galeno",
    "apotecario",
    "Navegante",
    "gu&iacute;a",
    "Alquimista",
    "astr&oacute;logo",
    "Esp&iacute;a",
    "diplom&aacute;tico",
    "Cart&oacute;grafo",
    "Inventor",
    "Pregonero",
    "Escudero",
    "arist&oacute;crata",
    "Alguacil",
    "sheriff",
    "jefe de la guardia",
    "Alcalde",
    "magistrado",
    "Sacerdote",
    "obispo",
    "abad",
    "Maestro gremial",
    "Caballero",
    "templario",
    "Sumo sacerdote",
    "Noble (bar&oacute;n, etc.)",
    "Alta nobleza",
    "Rey",
    "Reina",
    "Alquimista",
    "Herrero",
    "Carnicero",
    "Ladr&oacute;n",
    "Carpintero",
    "Cl&eacute;rigo",
    "Jugador",
    "Sepulturero",
    "Herbolario",
    "Cazador",
    "Mago",
    "Mercenario",
    "Comerciante",
    "Minero",
    "Forajido",
    "Ejecutante",
    "Carterista",
    "Contrabandista",
    "Siervo",
    "Guardabosques",
    "Aventurero",
    "Anticuario",
    "Artista",
    "Atleta",
    "Backwoodman",
    "Guardaespaldas",
    "Vagabundo",
    "Bur&oacute;crata",
    "Empresario",
    "Clero",
    "Estafador",
    "Vagabundo",
    "Ingeniero",
    "Animador",
    "Explorador",
    "Granjero",
    "Jugador",
    "G&aacute;ngster",
    "Obrero",
    "Abogado",
    "M&uacute;sico",
    "Ocultista",
    "Oficinista",
    "M&eacute;dico",
    "Piloto",
    "Polic&iacute;a",
    "Detective",
    "Profesor",
    "Programador",
    "Prostituta",
    "Psiquiatra",
    "Reportero",
    "Marinero",
    "Cient&iacute;fico",
    "Soldado",
    "Ama de casa",
    "C&oacute;nyuge",
    "Estudiante",
    "Ladr&oacute;n",
    "Fondo",
    "fiduciario",
    "Ni&ntilde;o",
    "Escritor",
    "Acad&eacute;mico",
    "Artista",
    "Escritor",
    "Coleccionista",
    "Rico",
    "Heredero",
    "Periodista",
    "Detective",
    "Cient&iacute;fico",
]; //let PROFESIONES_PNJ = [




let RASGOS_PNJ = [
    "Encantador",
    "Fr&iacute;o",
    "Caballeroso",
    "Brusco",
    "Desconfiado",
    "Obsesivo",
    "Astuto",
    "Callado",
    "Voluble",
    "Fiero",
    "Descuidado",
    "Reservado",
    "Despiadado",
    "Calculador",
    "Desafiante",
    "Amable",
    "Perspicaz",
    "Deshonesto",
    "Paciente",
    "Despiadado",
    "Sofisticado",
    "Paranoide",
    "Entusiasta",
    "Elitista",
    "Salvaje",
    "Cooperador",
    "Arrogante",
    "Confiado",
    "Vanidoso",
    "Atrevido",
    "Ventilocuo",
    "Musico",
    "Manitas",
    "Voluble",
    "Sincero",
    "Sutil",
    "Melanc&oacute;lico",
    "Enigm&aacute;tico",
    "Tranquilo",
    "Encantador de fuego",
    "Criado por Lobos",
    "Lunares",
    "Bailar&iacute;n de cuchillas",
    "Estrella bendecida",
    "El &uacute;ltimo veterano de guerra",
    "Alma antigua",
    "Portador de tormentas",
    "Uno con la noche",
    "Tocado por el drag&oacute;n",
    "Sobrevivi&oacute; al desierto de diamantes",
    "Fuerza de oso",
    "Se&ntilde;or de Quaruna",
    "Disc&iacute;pulo de la lengua plateada",
    "Ojos morados",
    "El pueblo de hierro",
    "Portador de arenisca",
    "Vida de servidumbre/opresi&oacute;n",
    "Pasaron ya sus mejores a&ntilde;os",
    "Experto en algo",
    "Vida peligrosa",
    "Vida privilegiada",
    "Especialista",
    "Inseguro",
    "racista",
    "xen&oacute;fobo",
    "Adicto",
    "Adicto dulces",
    "Adicto drogas",
    "Adicto sexo",
    "Fobia",
    "Fobia ara&ntilde;as",
    "Fobia fuego",
    "Fobia oscuridad",
    "Al&eacute;rgico",
    "asm&aacute;tico",
    "enfermo",
    "cr&oacute;nico",
    "Esc&eacute;ptico",
    "paranoide",
    "Supersticioso",
    "devoto",
    "fan&aacute;tico",
    "Taca&ntilde;o",
    "acaparador",
    "Derrochador",
    "gandul",
    "Pedante",
    "sabelotodo",
    "Art&iacute;stico",
    "so&ntilde;ador",
    "fantasioso",
    "C&aacute;ndido",
    "idealista",
    "Desfigurado (faltan dientes, un ojo, etc.)",
    "Lesi&oacute;n cr&oacute;nica",
    "(pierna o brazo torpe, etc.)",
    "Tatuado",
    "picado de viruelas",
    "cicatrices",
    "Desarreglado",
    "andrajoso",
    "mugriento",
    "Grande",
    "grueso",
    "fornido",
    "Peque&ntilde;o",
    "flacucho",
    "demacrado",
    "Pelo destacable (de punta, largo, etc.)",
    "Nariz destacable (grande, aguile&ntilde;a, etc.)",
    "Ojos destacables (azules, morados, enrojecidos, etc.)",
    "Pulcro bien vestido",
    "acicalado",
    "Atractivo",
    "guapo",
    "despampanante",
    "Solitario",
    "aislado",
    "antisocial",
    "Cruel",
    "beligerante",
    "abus&oacute;n",
    "Ansioso",
    "miedoso",
    "cobarde",
    "Envidioso",
    "codicioso",
    "avaricioso",
    "Fr&iacute;o",
    "altanero",
    "arrogante",
    "Torpe",
    "t&iacute;mido",
    "se odia a s&iacute; mismo",
    "Met&oacute;dico",
    "compulsivo",
    "controlador",
    "Seguro",
    "impulsivo",
    "imprudente",
    "Amable",
    "generoso",
    "compasivo",
    "Despreocupado",
    "relajado",
    "pac&iacute;fico",
    "Alegre",
    "feliz",
    "optimista",
    "Ambicioso",
    "Cauteloso",
    "Valiente",
    "Disciplinado",
    "Gregario",
    "Honorable",
    "Humilde",
    "Misericordioso",
    "Sereno",
    "Tolerante",
    "Agresivo",
    "Amargo",
    "Cobarde",
    "Enga&ntilde;oso",
    "Codicioso",
    "Perezoso",
    "Nervioso",
    "Grosero",
    "Vanidoso",
    "Vengativo",
    "Ambicioso",
    "Boor",
    "Peligroso",
    "Animador",
    "Honesto",
    "Holgaz&aacute;n",
    "Exc&eacute;ntrico",
    "Repulsivo",
    "Respetado",
    "Sabio",
    "Contundente",
    "Estruendoso",
    "Cr&iacute;ptico",
    "Zumbido",
    "Formal",
    "Grave",
    "Preciso",
    "Chirriante",
    "Tartamudeo",
    "Susurro",
    "Abandonado",
    "Adicto",
    "Chantajeado",
    "Condenado",
    "Degradado",
    "Expulsado",
    "Desacreditado",
    "Exiliado",
    "Enfermo",
    "Marcado",
    "Obsesionado",
    "Exc&eacute;ntrico",
    "Inquisitivo",
    "Enloquecido",
    "Ingenuo",
    "Sensible",
    "Esc&eacute;ptico",
    "Tenaz",
    "Prometedor",
    "Bien relacionado",
    "Respetado",
    "Con fondos",
    "Maldecido",
    "C&iacute;nico",
    "Atormentado",
    "Se&ntilde;alado",
    "Notorio",
    "Obsesionado",
]; //let RASGOS_PNJ



let INTERESES_PNJ = [
    "Whisky",
    "vino",
    "cerveza de calidad",
    "Comida",
    "restaurantes de calidad",
    "Ropa",
    "joyas",
    "pieles de calidad",
    "Bellas artes",
    "&oacute;pera",
    "teatro",
    "Pintura",
    "dibujo",
    "escultura",
    "Historia",
    "leyendas",
    "Arquitectura",
    "mobiliario",
    "Poes&iacute;a",
    "novelas",
    "escritura",
    "Luchar en los re&ntilde;ideros",
    "duelos",
    "Dioses olvidados",
    "Iglesia del &Eacute;xtasis",
    "Camino de los Ecos",
    "La Lagrimosa",
    "caridad",
    "Antigüedades",
    "artefactos",
    "curiosidades",
    "Caballos",
    "montar",
    "Artilugios",
    "nueva tecnolog&iacute;a",
    "Coleccionista de armas",
    "M&uacute;sica",
    "instrumentos",
    "baile",
    "Caza",
    "tiro",
    "Cocina",
    "jardiner&iacute;a",
    "Apuestas",
    "cartas",
    "dados",
    "Filosof&iacute;a natural",
    "Drogas",
    "esencias",
    "tabaco",
    "Amantes",
    "romance",
    "citas",
    "Fiestas",
    "eventos sociales",
    "Exploraci&oacute;n",
    "aventura",
    "Mascotas",
    "Arte",
    "marroquiner&iacute;a",
    "Barcos",
    "navegaci&oacute;n",
    "Pol&iacute;tica",
    "periodismo",
    "Libros",
    "rituales arcanos",
    "Espectrolog&iacute;a",
    "electroplasma",
    "Alquimia",
    "medicina",
    "Esencias",
    "alquimia",
    "Demonolog&iacute;a",
    "leyendas",
    "Robar",
    "Saquear",
    "Incendiar",
    "Guardar rencor",
    "Buscar venganza",
    "Cuestionar autoridad",
    "Prepotente",
    "Impulsivo",
    "Ceder a la tentaci&oacute;n",
    "Holgazanear",
    "Evitar el peligro o castigo",
    "Desacreditar lo paranormal",
    "Descubrir saberes perdidos",
    "Demostrar tu genialidad",
    "Ganar prestigio",
    "Obtener poderes prohibidos",
    "Perpetuar el legado familiar",
    "Salvar a la humanidad",
    "Descubrir la verdad",
]; //let INTERESES_PNJ = [




let PECULIARIDADES_PNJ = [
    "Supersticioso. Cree en se&ntilde;ales y n&uacute;meros m&aacute;gicos.",
    "Dedicado a su familia.",
    "Casado con una familia importante/poderosa.",
    "Mantiene su puesto para espiar a otra facci&oacute;n.",
    "Solitario. Prefiere interactuar a trav&eacute;s de otros.",
    "Grandes deudas (a bancos/criminales/familia).",
    "No ve los defectos de amigos, aliados, familia, etc&eacute;tera.",
    "Una vez fue una masa, pero luego se recuper&oacute;. Inmune a los esp&iacute;ritus.",
    "Tiene una enfermedad cr&oacute;nica que requiere cuidados frecuentes.",
    "Secretamente (&iquest;abiertamente?) controlado por un esp&iacute;ritu que lo posee.",
    "Cumple los planes de un demonio (a sabiendas o no).",
    "Orgulloso de su legado, tradiciones, lengua materna.",
    "Preocupado por las apariencias, los rumores, los compa&ntilde;eros.",
    "Abusa de las drogas/el alcohol. A menudo se ve afectado por su vicio.",
    "Mantiene su puesto gracias al chantaje.",
    "Depende del consejo para tomar decisiones.",
    "Involucrado en cr&iacute;menes de la Guerra de la Unidad.",
    "Lleva una doble vida usando una identidad falsa.",
    "Oveja negra/paria de una familia u organizaci&oacute;n.",
    "En prisi&oacute;n o bajo arresto domiciliario de un noble.",
    "Conocedor de mundo. Conexiones fuera de Doskvol.",
    "Revolucionario. Trama planes contra el Imperio.",
    "Ha heredado su posici&oacute;n. Puede que no la merezca/quiera.",
    "Famoso. Popularizado en prensa/m&uacute;sica/teatro.",
    "Mala reputaci&oacute;n (merecida o no).",
    "Rodeado de aduladores y lisonjeros.",
    "Reputaci&oacute;n intachable. Muy estimado.",
    "Prejuicios contra una cultura/creencia/clase social.",
    "Visionario. Tiene opiniones radicales sobre el futuro.",
    "Maldito, perseguido, acosado por esp&iacute;ritus o demonios.",
    "Fobia o aborrecimiento intensos e irracionales.",
    "Amplia educaci&oacute;n sobre cualquier tema acad&eacute;mico.",
    "Mantiene varios diarios detallados, notas, registros, libros de contabilidad.",
    "Es ciegamente fiel a un ideal, grupo o tradici&oacute;n.",
    "Profundamente tradicional. Opuesto a las nuevas ideas.",
    "Un fraude. Algunos aspectos importantes de su persona son falsos.",
    "Un poema para cada ocasi&oacute;n",
    "La espada de zafiro",
    "Encuentra a mi verdadera madre",
    "Una taza de t&eacute; de Nuna",
    "Un halc&oacute;n de las nieves",
    "La mayor&iacute;a de los problemas del Gremio",
    "Del Mar Negro",
    "Siempre lleva una daga oculta",
    "Un diente de drag&oacute;n blanco",
    "Derriba la tempestad",
    "La verdad est&aacute; sobrevalorada",
    "El pergamino que cambia de forma",
    "Restaura la fe del &Aacute;rbol Perdido",
    "Reflejos de un gato de plata",
    "El Amuleto de Jonaris",
    "El Pueblo Olvidado",
    "Nunca se quita la capucha",
    "Un reloj de nubes",
    "Recuperar la Primera Canci&oacute;n",
]; //let PECULIARIDADES_PNJ = [


let GRADOS_PNJ = [
    "magn&iacute;fico",
    "estupendo",
    "bueno",
    "justo/normal",
    "mediocre",
    "pobre/malo",
    "horrible"
]; //let GRADOS_PNJ = [


let APARIENCIAS_PNJ = [
    "Abierto",
    "Curtido",
    "Marcado",
    "Afable",
    "Delgado",
    "Melanc&oacute;lico",
    "Ajado",
    "Delicado",
    "Nervudo",
    "&Aacute;spero",
    "Encantador",
    "Oscuro",
    "Atl&eacute;tico",
    "Encorvado",
    "Rechoncho",
    "Atractivo",
    "Enorme",
    "Robusto",
    "Deslumbrante",
    "Esquel&eacute;tico",
    "Severo",
    "Calmado",
    "Feroz",
    "Fr&iacute;o",
    "Suave",
    "Sucio",
    "Cincelado",
    "Guapo",
    "Justo",
    "Triste",
    "Crispado",
    "L&aacute;nguido",
    "Abrigo",
    "Chaleco",
    "Pantalones de trabajo",
    "Capucha",
    "Chaqueta",
    "Planchado",
    "Abrigo grueso",
    "ligera",
    "Seda",
    "Auelta",
    "Abrigo largo",
    "Chaqueta",
    "Sombrero de tres picos",
    "Botas altas",
    "Ropa pesada",
    "Botas de terciopelo",
    "Cintur&oacute;n ancho",
    "Su&eacute;ter de terciopelo",
    "Botas de cuero",
    "Tirantes",
    "Esclavina",
    "Traje y corbata",
    "Bufanda larga",
    "Falda y blusa",
    "Trapos",
    "Gorro de lana",
    "jirones",
    "M&aacute;scara y Capa",
    "t&uacute;nica",
    "impermeable",
    "Media capa",
    "T&uacute;nica",
    "Capa pesada",
    "Mono",
    "Uniforme",
    "Pieles",
    "Pantalones ajustados",
    "Ajustado",
    "Velo",
    "Pantalones de trabajo"
]; //let APARIENCIAS_PNJ


var MOTIVACIONES = [
    "Servir a los poderosos",
    "Conseguir m&aacute;s poder/dinero/influencia",
    "Hacerme un nombre",
    "Vengar a un hermano/ progenitor/ser querido",
    "Destruir el sistema",
    "Proteger un lugar o establecimiento neutral",
    "Conseguir una dosis de sangre/drogas/sexo",
    "Encontrar la forma de poner fin a este r&eacute;quiem",
    "Deleitarme con el derroche sin sentido",
    "Proteger mi reputaci&oacute;n",
    "Resarcir a quien ha sufrido una injusticia",
    "Ofrecer perd&oacute;n a los culpables",
    "Descubrir la verdad sobre Watanabe",
    "Encontrar el ingrediente perfecto para un ritual",
    "Construir algo hermoso en Center City",
    "Terminar mi obra maestra",
    "Dar a los que no tienen suficiente",
    "Ascender puestos en la empresa",
    "Encontrar una forma de quedarme en esta ciudad/esta dimensi&oacute;n/este plano",
    "Volver a conectar con mi c&oacute;nyuge/amante tras habernos distanciado",
    "Compartir mi dolor con el mundo",
    "Vengarse",
    "Recibir alabanzas",
    "Difundir la palabra",
    "Descubrir la verdad",
    "Volver con un ser amado",
    "Salir bien parado de una apuesta",
    "Conseguir dinero",
    "Librarse de una obligaci&oacute;n",
    "Redimirse",
    "Convencer a alguien de que haga un trabajo sucio",
    "Explorar un lugar misterioso",
    "Descubrir una verdad oculta",
    "Robar algo valioso",
    "Encontrar algo perdido",
    "Superar una mala costumbre",
    "Matar a un enemigo odiado",
    "Cometer una atrocidad",
    "Conquistar una tierra lejana",
    "Obtener renombre",
    "Curar una enfermedad",
    "Acumular poder",
    "Crear una obra maestra",
    "Salvar a alguien de una monstruosidad",
    "Sobrevivir otro d&iacute;a",
    "Ense&ntilde;ar",
    "Conseguir afecto",
    "Sentar cabeza",
    "Demostrar algo",
    "Obtener un &uacute;ltimo bot&iacute;n",
    "Ser m&aacute;s listo, m&aacute;s fuerte, m&aacute;s r&aacute;pido",
    "Hacer cumplir la ley",
    "Curar una antigua herida",
    "Descubrir",
    "Acabar para siempre con un mal",
    "Devorar",
    "Esconderse de algo vergonzoso",
    "Limpiar el nombre de su familia",
    "Evangelizar",
    "Vivir una vida tranquila",
    "Extender el sufrimiento",
    "Ayudar a los dem&aacute;s",
    "Demostrar su val&iacute;a",
    "Desagraviar",
    "Ascender",
    "Demostrar su val&iacute;a",
    "Obtener honor",
    "Ser recordado en una canci&oacute;n",
    "Expandir sus tierras",
    "Ser olvidado",
    "Obtener un t&iacute;tulo",
    "Encontrar el amor verdadero",
    "Retirarse de la sociedad",
    "Perder la cabeza",
    "Escapar",
    "Darse el gusto",
    "Festejar",
    "Aprovechar lo que pueda",
    "Volver a casa",
    "Encontrarlo",
    "Servir",
    "Destruir un artefacto",
    "Reclamar lo que fue arrebatado",
    "Demostr&aacute;rselo a todos",
    "Hacer lo que hay que hacer",
    "Traer el verano eterno",
    "Ser un campe&oacute;n",
    "Volar",
    "Pasar desapercibido",
    "Encontrar al hombre con seis dedos",
    "Ayudar a un familiar",
    "Despertar a los primigenios",
    "Perfeccionar una habilidad",
    "Entretener",
    "Viajar",
    "Cumplir una orden",
    "Superar una desventaja",
    "Morir de manera gloriosa",
    "Conocer las reglas del juego",
    "Ser cuidadoso",
    "Fundar una dinast&iacute;a",
    "Ser bondadoso",
    "Mejorar el reino",
    "No fastidiarlo todo",
    "Retirarse",
    "Descubrir el pasado",
    "Recuperar los recuerdos perdidos",
    "Llegar donde nadie ha llegado",
    "Combatir",
    "Hacer el bien",
    "Convertirse en el terror de los criminales",
    "Convertirse en una bestia",
    "Derramar sangre",
    "Criar dragones",
    "Vivir eternamente",
    "Estar a la altura",
    "Cazar la presa m&aacute;s peligrosa",
    "Convertirse en alguien",
    "Odiar",
    "Hacer lo que hay que hacer",
    "Huir"
];
