let TESOROS = [
    "Azurita (opaca, azul oscuro moteado)",
    "&Aacute;gata con franjas (transl&uacute;cida, con rayas marrones, azules, b lancas o rojas)",
    "Cuarzo azul (transparente, azul p&aacute;lido)",
    "Ojo de &aacute;gata (transl&uacute;cido, c&iacute;rculos grises, blancos, ma rrones, azules o verdes)",
    "Hematita (opaca, gris-negra)",
    "Lapisl&aacute;zuli (opaco, azul claro y oscuro con motas amarillas)",
    "Malaquita (opaca, estr&iacute;as de verde claro y oscuro)",
    "&Aacute;gata musgosa (transl&uacute;cida, rosa o blanco amarillento con trazos musgosos verdes o grises Obsidiana (opaca, negro)",
    "Rodocrosita (opaca, rosa p&aacute;lido)",
    "Ojo de tigre (transl&uacute;cido, marr&oacute;n con n&uacute;cleo dorado)",
    "Turquesa (opaca, azul-verde claro)",
    "Jaspe sangu&iacute;neo (opaco, gris oscuro con motas rojas)",
    "Cornalina (opaca, de naranja a marr&oacute;n rojizo)",
    "Calcedonia (opaca , blanco)",
    "Bolsita de oro en polvo",
    "Crisoprasa (transl&uacute;cida, verde)",
    "Citrino (transparente, amarillo-marr&oacute;n p&aacute;lido)",
    "Jaspe (opaco, azul, negro o marr&oacute;n)",
    "Piedra de luna (transl&uacute;cida, blanco con b rillos azulados)",
    "&Oacute;nice (opaco, blanco, negro, o con franjas de am bos colores)",
    "Cuarzo (transparente, blanco, gris turbio o amarillo)",
    "Sard&oacute;nice (opaco, franjas rojas y blancas)",
    "Cuarzo rosa estrellado (transl&uacute;cido, piedra ros&aacute;cea con n&uacute;cleo en forma de estrella blanca)",
    "Zirconita (transparente, azul verdoso p&aacute;lido)",
    "&Aacute;mbar (transparente, dorado acuoso a dorado profundo)",
    "Amatista (transparente, p&uacute;rpura profundo)",
    "Crisoberilo (transparente, de amarillo verdoso a verde p&aacute;lido)",
    "Coral (opaco, carmes&iacute;)",
    "Granate (transparente, rojo, marr&oacute;n verdoso o violeta)",
    "Jade (transl&uacute;cido, verde claro, verde oscuro o blanco)",
    "Azabache (opaco, negro profundo)",
    "Perla (opaco, blanco lustroso, amarillo o rosa)",
    "Espinela (transparente, rojo, marr&oacute;n rojizo o verde oscuro)",
    "Turmalina (transparente, verde p&aacute;lido, azul, marr&oacute;n o rojo)",
    "Descripci&oacute;n de la gema Alejandrita (transparente, verde oscuro)",
    "Aguamarina (transparente, azul verdoso p&aacute; lido)",
    "Perla negra (opaco, negro puro)",
    "Espinela azul (transparente, azul oscuro)",
    "Peridoto (transparente, verde aceit una profundo)",
    "Topacio (transparente, amarillo dorado)",
    "&Oacute;palo negro (transl&uacute;cido, verde oscuro con moteado negro y vetas doradas)",
    "Zafiro azul (transparente, azul-blanco a azul medio)",
    "Esmeralda (transparente, verde profundo y brillante)",
    "&Oacute;palo de fuego (transl&uacute;cido, rojo fuego)",
    "&Oacute;palo (transl&uacute;cido, azul p&aacute;lido con moteado verde y dorado)",
    "Rub&iacute; estrella (transl&uacute;cido, rub&iacute; con n&uacute;cleo en forma de estrella blanca)",
    "Zafiro estrella (transl&uacute;cido, zafiro azul con n&uacute;cleo en forma de estrel la blanca)",
    "Zafiro amarillo (transparente, amarillo fuego o amaril lo verdoso)",
    "Zafiro negro (transl&uacute;cido, negro lu stroso con detalles luminosos)",
    "Diamante (transparente, azul-blanco, amarillo canario, rosa, marr&oacute;n o azul)",
    "Jacinto (transparente, naranja fuego)",
    "Rub&iacute; (transparente, rojo claro a rojo profundo)",
    "Aguamanil de plata",
    "Estatuilla tallada en hueso",
    "Brazalete de oro peque&ntilde;o",
    "Vestiduras de tela de oro",
    "M&aacute;scara de terciopelo negro bordada en plata",
    "C&aacute;liz de cobre con filigrana de plata",
    "Pareja de dados de hueso grabados",
    "Conjunto de espejos con marco de madera pintada",
    "Pa&ntilde;uelo de seda bordado",
    "Relicario con retrato pintado a mano dentro",
    "Anillo de oro con jaspe sangu&iacute;neo",
    "Estatuilla tallada en marfil",
    "Brazalete de oro grande",
    "Collar de plata con colgante de piedra preciosa",
    "Corona de bronce",
    "Bata de seda bordada en oro",
    "Tapiz grande y de calidad",
    "Jarra de lat&oacute;n con incrustaci&oacute;n de jade",
    "Caja de figuritas de animales de turquesa",
    "Jaula de p&aacute;jaro de oro, con filigrana",
    "C&aacute;liz de plata con piedras de luna incrustadas",
    "Espada de acero revestida en plata con un azabache incrustado en la empu&ntilde;adura",
    "Arpa tallada en madera ex&oacute;tica con incrustaciones de marfil y zirconitas",
    "&iacute;dolo de oro peque&ntilde;o",
    "Peine dorado con forma de drag&oacute;n, cuyos ojos son granates rojos",
    "Tap&oacute;n de vino repujado con pan de oro e incrustado con amatistas",
    "Daga ceremonial de electrum con perla negra en el pomo",
    "Broche de oro y plata",
    "Estatuilla de obsidiana con incrustaciones y relieves en oro",
    "M&aacute;scara de guerra de oro, pintada",
    "Cadena de oro fino con colgante de &oacute;palo de fuego",
    "Antigua obra maestra de la pintura",
    "Manto de terciopelo, con encaje de seda y numerosas piedras de luna engastadas",
    "Brazalete de platino con zafiro engastado",
    "Guante bordado con trozos de gema incrustados",
    "Ajorca de tobillo enjoyada",
    "Caja de m&uacute;sica de oro",
    "Diadema de oro con cuatro aguamarinas engastadas",
    "Parche de ojo con un ojo falso representado mediante zafiro azul y piedras de luna",
    "Collar de perlas rosas peque&ntilde;as",
    "Corona de oro con piedras preciosas incrustadas",
    "Anillo de platino con gemas",
    "Estatuilla de oro con rub&iacute;es engarzados",
    "Copa de oro con esmeraldas",
    "Joyero de oro con filigrana de platino",
    "Sarc&oacute;fago de ni&ntilde;o pintado en oro",
    "Tablero de juego de mesa de jade, con piezas de oro macizo",
    "Cuerno para beber de marfil, con filigrana de oro y cuajado de piedras preciosas",
    "Placeres carnales",
    "Un barril de leche de bicho",
    "Servicios mercenarios",
    "Un gato",
    "Papeletas de una rifa",
    "P&aacute;jaros cantores",
    "Un s&iacute;mbolo sagrado de gran valor",
    "Las llaves de la ciudad",
    "Trasgos amaestrados",
    "Los servicios de un especialista",
    "Un t&iacute;tulo nobiliario",
    "Revelar una ruta secreta que hace m&aacute;s f&aacute;cil y r&aacute;pido cruzar la zona",
    "Mu&ntilde;ecas y animales de peluche",
    "Tierras",
    "Ropa molona",
    "Tabaco a montones",
    "Un deseo, lo que sea",
    "Un instrumento musical",
    "Huevos",
    "Medicinas",
    "Perros",
    "Sedas",
    "Una esposa",
    "Ciudadan&iacute;a",
    "Pagar a un bardo para que escriba una canci&oacute;n sobre ellos y a otros bardos para que la aprendan e interpreten",
    "Augurios",
    "Rezar por ellos a los dioses",
    "Un disfraz",
    "Tapices o alfombras",
    "Animales ex&oacute;ticos",
    "Un puesto mejor en el M&aacute;s All&aacute;",
    "Arte",
    "La posibilidad de rezar en el santuario secreto del lugar",
    "Un beso del chico o la chica m&aacute;s agraciada del lugar",
    "Un cofre sorpresa",
    "Caballos",
    "Trabajo estable en el futuro",
    "Dulces caseros",
    "Armamento",
    "Un alma en botella",
    "Una pipa de fumar de lujo",
    "M&aacute;scaras",
    "Una piedra muy grande",
    "Incienso",
    "Lealtad eterna",
    "Acceso a una mazmorra secreta",
    "Vinos caros",
    "Un castillo en ruinas",
    "La propiedad de una mazmorra",
    "Le&ntilde;a en el norte, agua fresca en el sur",
    "Un esqueleto completo con los huesos unidos por alambre y colgado",
    "Un barril de encurtidos",
    "Comida",
    "Hospitalidad",
    "Licencias de caza o pesca",
    "Peinado, maquillaje, manicura y puesta a punto general",
    "Ganado",
    "Un secreto",
    "Una noche de juerga pagada",
    "Un libro valioso",
    "Un barco",
    "Una gema de un tipo poco valioso, pero est&uacute;pidamente grande",
    "Clases o entrenamiento",
    "Vales de descuento",
    "Un huevo misterioso",
    "Ojos de cristal",
    "Una receta familiar secreta",
    "Un monumento en su honor",
    "P&aacute;jaros de presa",
    "La promesa de servicios continuados como sanaci&oacute;n o remiendos",
    "Los serviccios de un int&eacute;rprete o traductor",
    "Reliquias con su relicario",
    "Mirra",
    "Repelente de monstruos",
    "Pergaminos que contienen t&eacute;cnicas de combate",
    "Un tatuaje",
    "Una fiesta en su honor",
    "Influencias",
    "Un palanqu&iacute;n",
    "Pan enano",
    "Una tumba para futuro uso",
    "Adopci&oacute;n en una familia pudiente",
    "Un juego de t&eacute; de porcelana del misterioso este",
    "Devolverte el favor haciendo otra aventura por ti",
    "Calaveras de colores",
    "Un banquete",
    "Una vieja llave",
    "Juego de instrumentos &oacute;pticos (lupa, catalejo, telescopio",
    "Esclavos",
    "Libros m&aacute;s o menos comunes",
    "Sus m&aacute;s sentidos agradecimientos",
    "Viaje con los gastos pagados a un sitio tropical",
    "Un conjuro secreto",
    "Un carruaje con sus caballer&iacute;as",
    "Un mapa",
    "Permiso para colonizar nuevas tierras",
    "Pelo humano",
    "Librarse de alguien",
    "Acceso a una instituci&oacute;n elitista",
    "Experiencia y exposici&oacute;n",
    "Pan enano",
    "Una tumba para futuro uso",
    "Adopci&oacute;n en una familia pudiente",
    "Un juego de t&eacute; de porcelana del misterioso este",
    "Devolverte el favor haciendo otra aventura por ti",
    "Calaveras de colores",
    "Un banquete",
    "Una vieja llave",
    "Juego de instrumentos &oacute;pticos (lupa, catalejo, telescopio",
    "Esclavos",
    "Libros m&aacute;s o menos comunes",
    "Sus m&aacute;s sentidos agradecimientos",
    "Viaje con los gastos pagados a un sitio tropical",
    "Un conjuro secreto",
    "Un carruaje con sus caballer&iacute;as",
    "Un mapa",
    "Permiso para colonizar nuevas tierras",
    "Pelo humano",
    "Librarse de alguien",
    "Acceso a una instituci&oacute;n elitista",
    "Experiencia y exposici&oacute;n",
    "Una mesa de oro cuyas patas son carneros de lapisl&aacute;zuli",
    "La corona de una concubina real, adornada con hojas de oro",
    "Copa de oro con pajita incluida",
    "Estatua de medio metro de marfil de un rey antiguo",
    "Sello de oro con el delicado dise&ntilde;o de un le&oacute;n moribundo",
    "Cabezas de &eacute;bano, talladas en un extra&ntilde;o estilo extranjero",
    "Gran bol de oro con diamantes incrustados mostrando posiciones astrol&oacute;gicas",
    "Estela con un complicado relieve militar y textos sobre gobernantes olvidados",
    "Un bloque de lapisl&aacute;zuli en bruto",
    "Antiguas fichas de cuentas hechas de materiales preciosos",
    "Un tablero de un juego de mesa labrado en alabastro",
    "Tarros ornados llenos de valiosos aceites perfumados",
    "Delgados lazos de oro y anillos dse plata decorados, dignos de rodear las barbas de un rey",
    "Una fortuna en peque&ntilde;os conejos de plata",
    "Rollos de tela p&uacute;rpura tra&iacute;da de Fenicia, te&ntilde;ida con pigmentos desconocidos",
    "Mirra",
    "Vasos de cristal de roca finamente esculpidos",
    "Un amuleto de protecci&oacute;n con toda clase de materiales preciosos, de mucha ayuda contra los diab&oacute;licos uttuku",
    "Espera, &iquest;es esto?",
    "Sandalias doradas",
    "Unas enormes puertas de cedro con exquisitas tallas",
]; //let TESOROS = [



function print_tesoros(element_id) {
    var element = document.getElementById(element_id);
    if (!element) return;

    var html_code = "";
    let cosa_text;

    for (let i=0; i<3; i++) {
        cosa_text = random_from_list(TESOROS);

        if (i > 0) {
            html_code += '<br/>';
        } //if (i > 0) {

        html_code += print_fortune_cookie(cosa_text);
    }; //for (let i=0; i<3; i++) {

    element.innerHTML = html_code;
    element.scrollTop = "0";
} //function print_tesoros(element_id)
